from __future__ import annotations

import argparse
import contextlib
import json
import math
import sys
import time
from pathlib import Path
from typing import Any, Optional, Tuple
from collections import Counter
from collections.abc import Iterable, Iterator

import torch
from torch.utils.data import DataLoader, Subset

try:
    from tqdm import tqdm  # type: ignore
except Exception:  # pragma: no cover
    tqdm = None


def _ensure_project_root_on_path() -> None:
    """在脚本直跑时确保仓库根目录可导入。"""

    # When running as: python3 batch_inference_motion_prosody.py
    # sys.path[0] is already the repo root, but keeping it explicit avoids
    # import surprises when this module is reached through compatibility shims.
    project_root = Path(__file__).resolve().parent
    project_root_str = str(project_root)
    if project_root_str not in sys.path:
        sys.path.insert(0, project_root_str)


_ensure_project_root_on_path()

from audio_aug import normalize_wav
from data import CachedMotionAudioDataset, collate
from manifest_utils import (
    EMOTIONS,
    load_split_manifest,
    manifest_sha256,
    normalize_seq as _shared_normalize_seq,
    parse_intensity as _shared_parse_intensity,
    read_xlsx_rows as _shared_read_xlsx_rows,
    resolve_label_en as _shared_resolve_label_en,
    resolve_paths_for_seq as _shared_resolve_paths_for_seq,
    select_manifest_items,
)
from metrics_utils import classification_summary, speaker_majority_baseline
from models import FusionClassifier
from path_utils import default_databases_dir, default_xlsx_path
from prosody import ProsodyConfig, extract_prosody_features
from predecode_motion_audio import load_audio
from runtime_adapt import (
    detect_runtime,
    resolve_amp_mode,
    resolve_batch_size,
    resolve_prefetch_factor,
    resolve_worker_count,
    select_device,
)
from video_motion import MotionConfig, RgbConfig, compute_face_flow_and_rgb_tensors, compute_face_flow_tensor, compute_face_rgb_tensor


def _read_xlsx_rows(path: Path) -> list[dict[str, Any]]:
    """复用 shared manifest 的 XLSX 读取逻辑。"""

    return _shared_read_xlsx_rows(path)


def _parse_intensity(raw: Any) -> Optional[float]:
    """复用 shared manifest 的强度解析逻辑。"""

    return _shared_parse_intensity(raw)


def _macro_f1_counts(tp: list[int], fp: list[int], fn: list[int]) -> float:
    """根据每类 TP/FP/FN 直接计算 macro-F1。"""

    k = len(tp)
    if k <= 0:
        return 0.0
    s = 0.0
    for i in range(k):
        denom = 2 * tp[i] + fp[i] + fn[i]
        s += (2 * tp[i] / denom) if denom > 0 else 0.0
    return float(s / k)


def _ccc(x: torch.Tensor, y: torch.Tensor) -> float:
    """计算连续强度回归的 CCC 指标。"""

    x = x.flatten().to(torch.float64)
    y = y.flatten().to(torch.float64)
    n = int(x.numel())
    if n < 2:
        return 0.0
    mx = float(x.mean().item())
    my = float(y.mean().item())
    vx = float(x.var(unbiased=False).item())
    vy = float(y.var(unbiased=False).item())
    cov = float(((x - mx) * (y - my)).mean().item())
    denom = vx + vy + (mx - my) ** 2
    if denom <= 0:
        return 0.0
    return float((2.0 * cov) / denom)


def _normalize_seq(raw: Any) -> str:
    """复用 shared manifest 的序号标准化逻辑。"""

    return _shared_normalize_seq(raw)


def _resolve_label_en(row: Any) -> Optional[str]:
    """从一条 XLSX 风格记录里解析英文标签。"""

    return _shared_resolve_label_en(row.get("情感类别"))


def _paths_for_seq(data_root: Path, label_en: str, seq: str) -> Tuple[Optional[Path], Optional[Path]]:
    """根据数据根目录、标签和序号推断媒体文件路径。"""

    return _shared_resolve_paths_for_seq(data_root, label_en, seq)


def parse_args() -> argparse.Namespace:
    """解析批量推理命令行参数。"""

    repo_root = Path(__file__).resolve().parent
    p = argparse.ArgumentParser(
        description="Batch inference for motion_prosody (flow/rgb + audio + prosody) from XLSX (序号/蒙文/中文/情感类别)"
    )
    p.add_argument("--data-root", type=Path, default=default_databases_dir(repo_root))
    p.add_argument("--xlsx", type=Path, default=default_xlsx_path(repo_root, "video_databases.xlsx"))
    p.add_argument(
        "--split-manifest",
        type=Path,
        default=None,
        help="Optional split manifest JSON generated by build_split_manifest.py",
    )
    p.add_argument(
        "--subset",
        type=str,
        default="all",
        choices=["all", "train", "val"],
        help="Subset to evaluate when --split-manifest is provided",
    )
    p.add_argument(
        "--benchmark-tag",
        type=str,
        default="default",
        help="Free-form benchmark name recorded in metrics output",
    )
    p.add_argument(
        "--cached-dataset",
        type=Path,
        default=None,
        help=(
            "If set, run inference from predecoded shards (outputs of predecode_motion_audio.py). "
            "This avoids OpenCV/video decoding entirely and is the recommended mode on servers where cv2 segfaults. "
            "Can be a directory containing *.pt shards, or a single shard file."
        ),
    )
    p.add_argument("--feature-cache", type=Path, default=None, help="Optional GPU feature-cache built by build_feature_cache.py")
    p.add_argument("--checkpoint", type=Path, default=Path("outputs/motion_prosody/checkpoints/best.pt"))
    p.add_argument("--output", type=Path, default=Path("outputs/motion_prosody/inference_results.jsonl"))
    p.add_argument("--device", type=str, default="auto", choices=["auto", "cuda", "cpu"])
    p.add_argument("--batch-size", type=str, default="auto")
    p.add_argument("--num-workers", type=str, default="auto")
    p.add_argument("--prefetch-factor", type=str, default="auto")

    p.add_argument(
        "--zero-video",
        action="store_true",
        help=(
            "Do NOT use OpenCV / video decoding. Instead, use an all-zero flow tensor. "
            "This is a safety switch to avoid OpenCV segfaults on some servers."
        ),
    )
    p.add_argument("--zero-audio", action="store_true", help="Zero audio-derived inputs (wav/audio_emb + prosody)")
    p.add_argument("--zero-text", action="store_true", help="Drop the text branch by passing no text input")
    p.add_argument(
        "--ablation",
        type=str,
        default="full",
        choices=["full", "text-only", "audio-only", "video-only", "no-text", "no-audio", "no-video"],
        help="Convenience preset for common modality ablations",
    )
    p.add_argument(
        "--skip-video-encoder",
        action="store_true",
        help=(
            "Skip the Conv3D video encoder entirely and use a zero video embedding. "
            "Use this on macOS/MPS because Conv3D is not supported on MPS. "
            "Also avoids any OpenCV/video decoding work."
        ),
    )

    p.add_argument("--num-frames", type=int, default=64)
    p.add_argument("--flow-size", type=int, default=112)
    p.add_argument("--rgb-size", type=int, default=224)
    p.add_argument("--sample-rate", type=int, default=24000)
    p.add_argument("--max-audio-sec", type=float, default=6.0)
    p.add_argument(
        "--audio-backend",
        type=str,
        default="auto",
        choices=["auto", "torchaudio", "soundfile"],
        help="Audio loading backend. auto=try torchaudio then fallback to soundfile",
    )
    p.add_argument("--prosody-no-pitch", action="store_true", help="Disable pitch extraction (faster)")

    p.add_argument("--limit", type=int, default=0, help="If >0, only run first N rows")
    p.add_argument("--fail-fast", action="store_true", help="Stop at first decode/predict error")
    p.add_argument("--no-amp", action="store_true", help="Disable AMP during inference")
    p.add_argument(
        "--amp-mode",
        type=str,
        default="auto",
        choices=["auto", "off", "fp16", "bf16"],
        help="Automatic mixed precision mode. auto prefers bf16 then fp16 on CUDA.",
    )
    p.add_argument(
        "--print-every",
        type=int,
        default=20,
        help="Print progress every N processed samples (0=disable; --debug prints every sample)",
    )
    p.add_argument(
        "--print-json",
        action="store_true",
        help="Also print each JSONL record when it is printed to console",
    )
    p.add_argument(
        "--print-result",
        type=str,
        default="none",
        choices=["none", "ok", "skip", "error", "all"],
        help="Print per-sample status lines: none/ok/skip/error/all",
    )
    p.add_argument(
        "--print-per-sample",
        action="store_true",
        help=(
            "Print decode+inference status for every sample (START + OK/MISS/SKIP/ERROR). "
            "This implies --print-result all, --stage-log, and disables tqdm progress bar."
        ),
    )
    p.add_argument(
        "--print-text",
        action="store_true",
        help="When printing per-sample logs, also print the Mongolian text (XLSX column: 蒙文).",
    )
    p.add_argument(
        "--text-max-len",
        type=int,
        default=0,
        help="If >0, truncate printed text fields to this length (0=do not truncate).",
    )

    # Text encoder settings (must match training)
    p.add_argument(
        "--text-model",
        type=str,
        default="",
        help=(
            "HF model name for the mBERT text encoder. If empty, try to read from checkpoint args; "
            "fallback to bert-base-multilingual-cased."
        ),
    )
    p.add_argument(
        "--max-text-len",
        type=int,
        default=128,
        help="Tokenizer max_length for Mongolian text (truncation enabled)",
    )
    p.add_argument(
        "--audio-model",
        type=str,
        default="",
        help="HF model name for audio encoder. If empty, read from checkpoint args.",
    )
    p.add_argument(
        "--fusion-mode",
        type=str,
        default="",
        choices=["", "gated_text", "concat"],
        help="Fusion mode override. If empty, read from checkpoint args.",
    )
    p.add_argument(
        "--gate-temperature",
        type=float,
        default=0.0,
        help="Gate temperature override (>0). If 0, read from checkpoint args.",
    )
    p.add_argument(
        "--gate-scale",
        type=float,
        default=0.0,
        help="Gate scale override. If 0, read from checkpoint args.",
    )
    p.add_argument(
        "--delta-scale",
        type=float,
        default=0.0,
        help="Delta scale override. If 0, read from checkpoint args.",
    )
    p.add_argument(
        "--modality-dropout",
        type=float,
        default=-1.0,
        help="Modality dropout override (use <0 to keep checkpoint value)",
    )
    p.add_argument(
        "--video-backbone",
        type=str,
        default="",
        choices=["", "flow", "videomae", "dual"],
        help="Video backbone to use. If empty, read from checkpoint args.",
    )
    p.add_argument(
        "--video-model",
        type=str,
        default="",
        help="HF model name for VideoMAE. If empty, read from checkpoint args.",
    )
    p.add_argument(
        "--show-first-errors",
        type=int,
        default=10,
        help="Print the first N error messages immediately (helps diagnose why ok=0)",
    )
    p.add_argument(
        "--no-progress",
        action="store_true",
        help="Disable tqdm progress bar",
    )
    p.add_argument(
        "--stage-log",
        action="store_true",
        help="Print per-sample stage logs (useful when flow extraction is slow)",
    )
    p.add_argument("--debug", action="store_true", help="Print per-sample debug info (slower)")
    return p.parse_args()


def _load_model(ckpt_path: Path, device: torch.device, args: argparse.Namespace) -> tuple[FusionClassifier, bool]:
    """加载 checkpoint，并从其中恢复默认推理配置。

    推理侧默认优先相信 checkpoint 里的训练参数，只在用户显式传入
    CLI override 时覆盖它们。
    """

    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    state = ckpt["model"] if isinstance(ckpt, dict) and "model" in ckpt else ckpt

    text_model = "bert-base-multilingual-cased"
    audio_model = "wav2vec2_base"
    video_backbone = "dual"
    video_model = "MCG-NJU/videomae-large"
    fusion_mode = "gated_text"
    gate_temperature = 1.0
    gate_scale = 1.0
    delta_scale = 1.0
    modality_dropout = 0.0
    use_intensity = False
    if isinstance(ckpt, dict):
        ckpt_args = ckpt.get("args", None)
        if isinstance(ckpt_args, dict):
            tm = ckpt_args.get("text_model", "")
            if isinstance(tm, str) and tm.strip():
                text_model = tm.strip()
            am = ckpt_args.get("audio_model", "")
            if isinstance(am, str) and am.strip():
                audio_model = am.strip()
            vb = ckpt_args.get("video_backbone", "")
            if isinstance(vb, str) and vb.strip():
                video_backbone = vb.strip()
            vm = ckpt_args.get("video_model", "")
            if isinstance(vm, str) and vm.strip():
                video_model = vm.strip()
            fm = ckpt_args.get("fusion_mode", "")
            if isinstance(fm, str) and fm.strip():
                fusion_mode = fm.strip()
            try:
                gate_temperature = float(ckpt_args.get("gate_temperature", gate_temperature))
            except Exception:
                pass
            try:
                gate_scale = float(ckpt_args.get("gate_scale", gate_scale))
            except Exception:
                pass
            try:
                delta_scale = float(ckpt_args.get("delta_scale", delta_scale))
            except Exception:
                pass
            try:
                modality_dropout = float(ckpt_args.get("modality_dropout", modality_dropout))
            except Exception:
                pass
            use_intensity = bool(ckpt_args.get("use_intensity", False))

    # CLI overrides
    if isinstance(getattr(args, "text_model", ""), str) and str(args.text_model).strip():
        text_model = str(args.text_model).strip()
    if isinstance(getattr(args, "audio_model", ""), str) and str(args.audio_model).strip():
        audio_model = str(args.audio_model).strip()
    if isinstance(getattr(args, "video_backbone", ""), str) and str(args.video_backbone).strip():
        video_backbone = str(args.video_backbone).strip()
    if isinstance(getattr(args, "video_model", ""), str) and str(args.video_model).strip():
        video_model = str(args.video_model).strip()
    if isinstance(getattr(args, "fusion_mode", ""), str) and str(args.fusion_mode).strip():
        fusion_mode = str(args.fusion_mode).strip()
    if isinstance(getattr(args, "gate_temperature", 0.0), (int, float)) and float(args.gate_temperature) > 0:
        gate_temperature = float(args.gate_temperature)
    if isinstance(getattr(args, "gate_scale", 0.0), (int, float)) and float(args.gate_scale) != 0:
        gate_scale = float(args.gate_scale)
    if isinstance(getattr(args, "delta_scale", 0.0), (int, float)) and float(args.delta_scale) != 0:
        delta_scale = float(args.delta_scale)
    if isinstance(getattr(args, "modality_dropout", -1.0), (int, float)) and float(args.modality_dropout) >= 0:
        modality_dropout = float(args.modality_dropout)

    # 推理阶段不关心 requires_grad，但某些编码器初始化路径仍然需要 freeze 参数。
    model = FusionClassifier(
        num_classes=len(EMOTIONS),
        freeze_audio=True,
        text_model=text_model,
        freeze_text=True,
        audio_model=audio_model,
        video_backbone=video_backbone,
        video_model=video_model,
        fusion_mode=fusion_mode,
        gate_temperature=gate_temperature,
        gate_scale=gate_scale,
        delta_scale=delta_scale,
        modality_dropout=modality_dropout,
    )
    # Allow loading older classification-only checkpoints that don't have regression head weights.
    missing, unexpected = model.load_state_dict(state, strict=False)
    if missing or unexpected:
        # Keep it informative but not too noisy.
        if missing:
            print(f"WARNING: missing keys when loading checkpoint: {missing[:6]}" + (" ..." if len(missing) > 6 else ""), flush=True)
        if unexpected:
            print(
                f"WARNING: unexpected keys when loading checkpoint: {unexpected[:6]}" + (" ..." if len(unexpected) > 6 else ""),
                flush=True,
            )
    model.to(device)
    model.eval()
    return model, bool(use_intensity)


def _select_device() -> torch.device:
    """Prefer CUDA, then MPS (macOS), otherwise CPU."""

    if torch.cuda.is_available():
        return torch.device("cuda")
    # MPS is available on macOS when torch is built with MPS and a supported GPU exists.
    try:
        if getattr(torch.backends, "mps", None) is not None:
            if torch.backends.mps.is_available() and torch.backends.mps.is_built():
                return torch.device("mps")
    except Exception:
        pass
    return torch.device("cpu")


def _resolve_ablation_flags(args: argparse.Namespace) -> tuple[bool, bool, bool]:
    """把消融预设翻译成最终的 zero-video / zero-audio / zero-text 开关。"""

    ablation = str(getattr(args, "ablation", "full") or "full").strip().lower()
    zero_video = bool(getattr(args, "zero_video", False))
    zero_audio = bool(getattr(args, "zero_audio", False))
    zero_text = bool(getattr(args, "zero_text", False))

    presets = {
        "full": (False, False, False),
        "text-only": (True, True, False),
        "audio-only": (True, False, True),
        "video-only": (False, True, True),
        "no-text": (False, False, True),
        "no-audio": (False, True, False),
        "no-video": (True, False, False),
    }
    preset = presets.get(ablation)
    if preset is not None:
        zero_video = zero_video or preset[0]
        zero_audio = zero_audio or preset[1]
        zero_text = zero_text or preset[2]
    return zero_video, zero_audio, zero_text


def _forward_outputs(
    model: FusionClassifier,
    flow: Optional[torch.Tensor],
    rgb: Optional[torch.Tensor],
    wav: torch.Tensor,
    prosody: torch.Tensor,
    text_inputs: Optional[dict[str, torch.Tensor]],
    audio_lens: Optional[torch.Tensor],
    audio_emb: Optional[torch.Tensor],
    flow_emb: Optional[torch.Tensor],
    rgb_emb: Optional[torch.Tensor],
    text_emb: Optional[torch.Tensor],
    device: torch.device,
    use_amp: bool,
    amp_mod: Any,
    skip_video_encoder: bool,
    return_intensity: bool,
    video_backbone: str,
) -> tuple[torch.Tensor, Optional[torch.Tensor], str]:
    """Forward pass with an option to bypass the Conv3D video encoder."""

    if device.type == "cuda":
        if amp_mod is not None and hasattr(amp_mod, "autocast"):
            amp_ctx = amp_mod.autocast("cuda", enabled=use_amp)  # type: ignore[attr-defined]
        else:
            amp_ctx = torch.cuda.amp.autocast(enabled=use_amp)
    else:
        amp_ctx = contextlib.nullcontext()

    with torch.no_grad(), amp_ctx:
        if skip_video_encoder:
            # 这个分支用于“显式绕过视频编码器”的推理：
            # 视频向量直接置零，只保留其它模态前向。
            if audio_emb is not None:
                a = audio_emb.to(dtype=wav.dtype)
            else:
                a = model.audio(wav)
            p = model.prosody(prosody)
            try:
                video_dim = int(getattr(model, "video_out_dim", 256))
            except Exception:
                video_dim = 256
            v = torch.zeros((wav.shape[0], video_dim), device=wav.device, dtype=a.dtype)
            if text_inputs is None:
                try:
                    text_dim = int(getattr(model.text, "out_dim", 768))
                except Exception:
                    text_dim = 768
                t = torch.zeros((wav.shape[0], text_dim), device=wav.device, dtype=a.dtype)
            else:
                t = model.text(text_inputs).to(dtype=a.dtype)
            x = torch.cat([v, a, p, t], dim=1)
            logits = model.head(x)
            pred_intensity = None
            if bool(return_intensity):
                if getattr(model, "reg_head", None) is None:
                    raise RuntimeError("intensity_head_missing")
                pred_intensity = model.reg_head(x).squeeze(1)
            return logits, pred_intensity, "skip_encoder"

        if str(video_backbone) in {"videomae", "dual"} and rgb is None:
            raise ValueError("rgb_missing")
        if str(video_backbone) in {"flow", "dual"} and flow is None:
            raise ValueError("flow_missing")
        if bool(return_intensity):
            logits, pred_intensity = model(
                flow,
                wav,
                prosody,
                text_inputs=text_inputs,
                return_intensity=True,
                rgb=rgb,
                audio_lens=audio_lens,
                audio_emb=audio_emb,
                flow_emb=flow_emb,
                rgb_emb=rgb_emb,
                text_emb=text_emb,
            )
            return logits, pred_intensity, "full"
        logits = model(
            flow,
            wav,
            prosody,
            text_inputs=text_inputs,
            rgb=rgb,
            audio_lens=audio_lens,
            audio_emb=audio_emb,
            flow_emb=flow_emb,
            rgb_emb=rgb_emb,
            text_emb=text_emb,
        )
        return logits, None, "full"


def _iter_cached_paths(cached_dataset: Path) -> list[Path]:
    """把 cached shard 目录或单文件统一展开成路径列表。"""

    cached_dataset = cached_dataset.expanduser()
    if cached_dataset.is_file():
        paths = [cached_dataset]
    else:
        paths = sorted(
            cached_dataset.glob("*.pt"),
            key=lambda p: int(p.stem) if p.stem.isdigit() else p.stem,
        )
    if not paths:
        raise FileNotFoundError(f"No .pt shards found under {cached_dataset}")
    return paths


def _iter_cached_samples(paths: Iterable[Path]) -> Iterator[tuple[Path, dict[str, Any]]]:
    """Yield (shard_path, sample_dict) items, streaming one shard at a time."""

    for p in paths:
        obj = torch.load(p, map_location="cpu", weights_only=False)
        part = obj["samples"] if isinstance(obj, dict) and "samples" in obj else obj
        if not isinstance(part, list):
            raise RuntimeError(f"Unexpected shard format in {p}: expected list under 'samples'")
        for s in part:
            if isinstance(s, dict):
                yield p, s


def _count_cached_samples(paths: Iterable[Path]) -> int:
    """统计 cached shard 中的样本总数。"""

    total = 0
    for p in paths:
        obj = torch.load(p, map_location="cpu", weights_only=False)
        part = obj["samples"] if isinstance(obj, dict) and "samples" in obj else obj
        if isinstance(part, list):
            total += len(part)
    return int(total)


def _cache_text_tokens(ds: CachedMotionAudioDataset, tokenizer: Any, max_text_len: int) -> None:
    """预先把整集文本分词，避免 cached 推理重复 tokenizer。"""

    if not ds.samples:
        return
    if all("text_emb" in s for s in ds.samples):
        return
    if all("_text_input_ids" in s and "_text_attention_mask" in s for s in ds.samples):
        return
    enc = tokenizer(
        [str(s.get("mn", "")) for s in ds.samples],
        padding="max_length",
        truncation=True,
        max_length=int(max_text_len),
        return_tensors="pt",
    )
    token_type_ids = enc.get("token_type_ids", None)
    for idx, sample in enumerate(ds.samples):
        sample["_text_input_ids"] = enc["input_ids"][idx].to(torch.long).clone()
        sample["_text_attention_mask"] = enc["attention_mask"][idx].to(torch.long).clone()
        if token_type_ids is not None:
            sample["_text_token_type_ids"] = token_type_ids[idx].to(torch.long).clone()


def _run_cached_batched(
    *,
    ds: CachedMotionAudioDataset,
    subset_indices: list[int],
    out_file: Any,
    model: FusionClassifier,
    tokenizer: Any,
    args: argparse.Namespace,
    device: torch.device,
    use_amp: bool,
    amp_mod: Any,
    video_backbone: str,
    ckpt_use_intensity: bool,
    manifest_by_seq: dict[str, dict[str, Any]],
    print_result: str,
    print_every: int,
    show_first_errors: int,
) -> dict[str, Any]:
    """对 cached / feature-cache 数据做 batched 推理。"""

    eval_ds = Subset(ds, subset_indices) if subset_indices else ds
    profile = detect_runtime(str(args.device))
    using_feature_cache = bool(args.feature_cache is not None or ds.config.get("feature_cache"))
    resolved_batch_size = resolve_batch_size(
        args.batch_size,
        phase="inference",
        profile=profile,
        feature_cache=using_feature_cache,
        video_backbone=str(video_backbone),
        freeze_audio=True,
        freeze_text=True,
        freeze_flow=True,
        freeze_rgb=True,
    )
    resolved_num_workers = resolve_worker_count(
        args.num_workers,
        phase="inference",
        profile=profile,
        dataset_in_memory=True,
        total_items=(len(subset_indices) if subset_indices else len(ds)),
    )
    prefetch_factor = resolve_prefetch_factor(args.prefetch_factor, num_workers=resolved_num_workers)

    dl_kwargs: dict[str, Any] = {
        "batch_size": int(resolved_batch_size),
        "shuffle": False,
        "num_workers": int(resolved_num_workers),
        "collate_fn": collate,
        "pin_memory": device.type == "cuda",
    }
    if int(resolved_num_workers) > 0:
        dl_kwargs["persistent_workers"] = True
        if prefetch_factor is not None:
            dl_kwargs["prefetch_factor"] = int(prefetch_factor)
    loader = DataLoader(eval_ds, **dl_kwargs)

    ok_count = 0
    skip_count = 0
    err_count = 0
    correct = 0
    seen = 0
    y_true_indices: list[int] = []
    y_pred_indices: list[int] = []
    reg_true: list[float] = []
    reg_pred: list[float] = []
    err_types: Counter[str] = Counter()

    iterator = loader
    if tqdm is not None and (not args.no_progress):
        iterator = tqdm(loader, desc="Batch inference [cached]", unit="batch", dynamic_ncols=True)

    first_errors = 0
    for batch in iterator:
        nb = device.type == "cuda"
        stems = [str(x) for x in batch.get("stems", [])]
        labels = batch["labels"]
        speaker_ids = [str(x) for x in batch.get("speaker_id", ["UNKNOWN"] * labels.shape[0])]
        flow = batch.get("flow", None)
        rgb = batch.get("rgb", None)
        flow_emb = batch.get("flow_emb", None)
        rgb_emb = batch.get("rgb_emb", None)
        audio_emb = batch.get("audio_emb", None)
        wav = batch.get("audio", None)
        audio_lens = batch.get("audio_lens", None)
        prosody = batch["prosody"]
        text_emb = batch.get("text_emb", None)
        text_inputs = batch.get("text_inputs", None)

        try:
            if flow is not None:
                flow = flow.to(device, non_blocking=nb)
            if rgb is not None:
                rgb = rgb.to(device, non_blocking=nb)
            if flow_emb is not None:
                flow_emb = flow_emb.to(device, non_blocking=nb)
            if rgb_emb is not None:
                rgb_emb = rgb_emb.to(device, non_blocking=nb)
            if audio_emb is not None:
                audio_emb = audio_emb.to(device, non_blocking=nb)
            if wav is None:
                wav = torch.zeros((labels.shape[0], 1), device=device, dtype=torch.float32)
            else:
                wav = wav.to(device, non_blocking=nb)
            if audio_lens is not None:
                audio_lens = audio_lens.to(device, non_blocking=nb)
            prosody = prosody.to(device, non_blocking=nb)
            if text_emb is not None:
                text_emb = text_emb.to(device, non_blocking=nb)
            if text_inputs is not None:
                text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}
            elif text_emb is None and not bool(args.zero_text):
                text_inputs = tokenizer(
                    [str(x) for x in batch.get("mn", [])],
                    padding=True,
                    truncation=True,
                    max_length=int(args.max_text_len),
                    return_tensors="pt",
                )
                text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}

            if bool(args.zero_video):
                if flow is not None:
                    flow = torch.zeros_like(flow)
                if rgb is not None:
                    rgb = torch.zeros_like(rgb)
                if flow_emb is not None:
                    flow_emb = torch.zeros_like(flow_emb)
                if rgb_emb is not None:
                    rgb_emb = torch.zeros_like(rgb_emb)
            if bool(args.zero_audio):
                wav = torch.zeros_like(wav)
                prosody = torch.zeros_like(prosody)
                if audio_emb is not None:
                    audio_emb = torch.zeros_like(audio_emb)
            if bool(args.zero_text):
                text_inputs = None
                text_emb = None

            logits, pred_intensity, _forward_mode = _forward_outputs(
                model,
                flow,
                rgb,
                wav,
                prosody,
                text_inputs,
                audio_lens,
                audio_emb,
                flow_emb,
                rgb_emb,
                text_emb,
                device=device,
                use_amp=use_amp,
                amp_mod=amp_mod,
                skip_video_encoder=bool(args.skip_video_encoder),
                return_intensity=bool(ckpt_use_intensity),
                video_backbone=video_backbone,
            )
        except Exception as e:
            batch_n = int(labels.shape[0])
            err_count += batch_n
            err_types[type(e).__name__] += batch_n
            for i, stem in enumerate(stems):
                label_idx = int(labels[i].item())
                label_en = EMOTIONS[label_idx] if 0 <= label_idx < len(EMOTIONS) else None
                rec = {
                    "stem": stem,
                    "status": "error",
                    "label": label_en,
                    "error": f"{type(e).__name__}: {e}",
                    "cache_kind": "feature" if using_feature_cache else "raw_cached",
                }
                out_file.write(json.dumps(rec, ensure_ascii=False) + "\n")
                if first_errors < show_first_errors:
                    print(f"ERROR stem={stem} label={label_en} err={rec['error']}", flush=True)
                    first_errors += 1
            if args.fail_fast:
                raise
            continue

        probs = torch.softmax(logits, dim=1).detach().cpu()
        pred_indices = torch.argmax(probs, dim=1)
        pred_intensity_cpu = pred_intensity.detach().float().cpu() if pred_intensity is not None else None

        for i, stem in enumerate(stems):
            label_idx = int(labels[i].item())
            if not (0 <= label_idx < len(EMOTIONS)):
                skip_count += 1
                rec = {
                    "stem": stem,
                    "status": "skip",
                    "reason": "bad_label",
                    "label": label_idx,
                }
                out_file.write(json.dumps(rec, ensure_ascii=False) + "\n")
                continue

            seen += 1
            ok_count += 1
            label_en = EMOTIONS[label_idx]
            pred_idx = int(pred_indices[i].item())
            pred = EMOTIONS[pred_idx]
            prob = float(probs[i, pred_idx].item())
            match = bool(pred_idx == label_idx)
            correct += int(match)
            y_true_indices.append(label_idx)
            y_pred_indices.append(pred_idx)

            gt_intensity_val: Optional[float] = None
            pred_intensity_val: Optional[float] = None
            if bool(ckpt_use_intensity):
                try:
                    gt_value = float(batch["intensity"][i].item())
                    if math.isfinite(gt_value):
                        gt_intensity_val = gt_value
                        if pred_intensity_cpu is not None:
                            pred_intensity_val = float(pred_intensity_cpu[i].item())
                            reg_true.append(gt_value)
                            reg_pred.append(pred_intensity_val)
                except Exception:
                    gt_intensity_val = None

            rec = {
                "stem": stem,
                "status": "ok",
                "label": label_en,
                "pred": pred,
                "match": match,
                "probability": prob,
                "speaker_id": speaker_ids[i],
                "cache_kind": "feature" if using_feature_cache else "raw_cached",
                "mn": str(batch.get("mn", [""])[i]),
            }
            if bool(ckpt_use_intensity):
                rec["pred_intensity"] = pred_intensity_val
                rec["intensity_gt"] = gt_intensity_val
            out_file.write(json.dumps(rec, ensure_ascii=False) + "\n")

            if print_result in {"ok", "all"}:
                tag = "OK" if match else "MISS"
                print(f"{tag} stem={stem} label={label_en} pred={pred} p={prob:.4f}", flush=True)
            if print_every > 0 and (seen % int(print_every)) == 0:
                acc = correct / max(1, seen)
                print(f"[{seen}] acc={acc:.4f} stem={stem} label={label_en} pred={pred} p={prob:.4f}", flush=True)

    return {
        "correct": correct,
        "seen": seen,
        "ok_count": ok_count,
        "skip_count": skip_count,
        "err_count": err_count,
        "y_true_indices": y_true_indices,
        "y_pred_indices": y_pred_indices,
        "reg_true": reg_true,
        "reg_pred": reg_pred,
        "err_types": err_types,
        "resolved_batch_size": int(resolved_batch_size),
        "resolved_num_workers": int(resolved_num_workers),
        "resolved_prefetch_factor": int(prefetch_factor) if prefetch_factor is not None else None,
        "using_feature_cache": using_feature_cache,
    }


def main() -> None:
    """批量推理主流程。

    支持两条路径：
    1. cached 模式：直接读取预解码 shard，速度快且最稳定；
    2. raw XLSX 模式：按表格逐条在线提取视频/音频特征。

    最终会输出逐样本 JSONL 结果，以及一个同名 `.metrics.json` 汇总文件。
    """

    args = parse_args()

    data_root = args.data_root.expanduser()
    xlsx = args.xlsx.expanduser()
    cached_dataset = args.cached_dataset.expanduser() if args.cached_dataset is not None else None
    feature_cache = args.feature_cache.expanduser() if args.feature_cache is not None else None
    split_manifest_path = args.split_manifest.expanduser() if args.split_manifest is not None else None
    ckpt_path = args.checkpoint.expanduser()
    out_path = args.output.expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if split_manifest_path is not None and not split_manifest_path.exists():
        raise FileNotFoundError(f"Split manifest not found: {split_manifest_path}")
    if cached_dataset is None and feature_cache is None and split_manifest_path is None:
        if not xlsx.exists():
            raise FileNotFoundError(f"XLSX not found: {xlsx}")
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")

    zero_video, zero_audio, zero_text = _resolve_ablation_flags(args)
    args.zero_video = zero_video
    args.zero_audio = zero_audio
    args.zero_text = zero_text

    profile = detect_runtime(args.device)
    device = select_device(args.device)
    # Conv3D is not supported on MPS; by default, fall back to CPU for full-model inference.
    # If user explicitly asks to skip the video encoder, MPS can still be used for audio+prosody.
    if device.type == "mps" and (not bool(args.skip_video_encoder)):
        print(
            "WARNING: MPS selected but Conv3D video encoder is not supported on MPS. "
            "Falling back to CPU. Use --skip-video-encoder to run audio+prosody only on MPS.",
            flush=True,
        )
        device = torch.device("cpu")

    requested_amp_mode = "off" if bool(args.no_amp) else str(args.amp_mode)
    resolved_amp_mode = resolve_amp_mode(requested_amp_mode, profile)
    use_amp = resolved_amp_mode != "off" and device.type == "cuda"

    model, ckpt_use_intensity = _load_model(ckpt_path, device=device, args=args)
    video_backbone = str(getattr(model, "video_backbone", "flow"))

    try:
        from transformers import AutoTokenizer
    except Exception as e:
        raise RuntimeError(
            "transformers is required for tri-modal inference (text branch). Install with: pip install transformers"
        ) from e

    text_model_name = ""
    if isinstance(getattr(args, "text_model", None), str) and str(args.text_model).strip():
        text_model_name = str(args.text_model).strip()
    if not text_model_name:
        try:
            text_model_name = str(getattr(model.text, "model_name", "") or "")
        except Exception:
            text_model_name = ""
    if not text_model_name:
        text_model_name = "bert-base-multilingual-cased"
    tokenizer = AutoTokenizer.from_pretrained(text_model_name)

    rows: list[dict[str, Any]] = []
    manifest: dict[str, Any] | None = None
    manifest_items: list[dict[str, Any]] = []
    manifest_hash: str | None = None
    if split_manifest_path is not None:
        manifest = load_split_manifest(split_manifest_path)
        manifest_items = select_manifest_items(manifest, args.subset)
        manifest_hash = manifest_sha256(split_manifest_path)
    cached_input = feature_cache if feature_cache is not None else cached_dataset
    if cached_input is not None:
        if manifest_items:
            total = len(manifest_items)
        else:
            total = int(_count_cached_samples(_iter_cached_paths(cached_input)))
        limit = args.limit if args.limit and args.limit > 0 else total
    else:
        if manifest_items:
            rows = manifest_items
        else:
            rows = _read_xlsx_rows(xlsx)
        total = len(rows)
        limit = args.limit if args.limit and args.limit > 0 else total
    allowed_stems = {str(item.get("seq", "")) for item in manifest_items} if manifest_items else None
    manifest_by_seq = {str(item.get("seq", "")): item for item in manifest_items} if manifest_items else {}

    print(
        json.dumps(
            {
                "runtime": profile.to_jsonable(),
                "device": str(device),
                "amp_mode": resolved_amp_mode,
                "cached_input": str(cached_input) if cached_input is not None else None,
                "feature_cache": str(feature_cache) if feature_cache is not None else None,
            },
            ensure_ascii=False,
            indent=2,
        ),
        flush=True,
    )

    correct = 0
    seen = 0
    skipped = 0
    y_true_indices: list[int] = []
    y_pred_indices: list[int] = []

    # Macro-F1 counts over ok samples.
    tp = [0 for _ in range(len(EMOTIONS))]
    fp = [0 for _ in range(len(EMOTIONS))]
    fn = [0 for _ in range(len(EMOTIONS))]

    # Regression accumulators over samples with GT intensity.
    reg_pred: list[float] = []
    reg_true: list[float] = []

    amp_mod = getattr(torch, "amp", None)
    print_every = int(args.print_every)
    print_result = str(args.print_result or "none").lower().strip()
    show_first_errors = max(0, int(args.show_first_errors))

    def _fmt_text(x: Any) -> str:
        """把文本字段裁成适合日志打印的短字符串。"""

        s = "" if x is None else str(x)
        s = s.strip()
        max_len = int(getattr(args, "text_max_len", 0) or 0)
        if max_len > 0 and len(s) > max_len:
            return s[:max_len] + "…"
        return s

    if bool(args.print_per_sample):
        print_result = "all"
        args.stage_log = True
        args.no_progress = True
        args.print_text = True
        # ensure periodic prints don't hide per-sample logs
        if print_every <= 0:
            print_every = 1

    # If user wants per-sample prints, tqdm becomes redundant/noisy.
    if print_result != "none":
        args.no_progress = True

    # Stage logs help avoid the impression of being stuck during heavy per-sample compute.
    stage_log = bool(args.stage_log) or bool(args.debug)

    ok_count = 0
    skip_count = 0
    err_count = 0
    err_types: Counter[str] = Counter()
    first_errors: list[str] = []
    cached_run_stats: dict[str, Any] = {}

    with open(out_path, "w", encoding="utf-8") as f:
        if cached_input is not None:
            ds = CachedMotionAudioDataset(cached_input)
            subset_indices = list(range(len(ds)))
            if allowed_stems is not None:
                subset_indices = [idx for idx, sample in enumerate(ds.samples) if str(sample.get("stem", "")) in allowed_stems]
            if limit > 0:
                subset_indices = subset_indices[:limit]
            if (not bool(args.zero_text)) and tokenizer is not None:
                _cache_text_tokens(ds, tokenizer, int(args.max_text_len))

            cached_run_stats = _run_cached_batched(
                ds=ds,
                subset_indices=subset_indices,
                out_file=f,
                model=model,
                tokenizer=tokenizer,
                args=args,
                device=device,
                use_amp=use_amp,
                amp_mod=amp_mod,
                video_backbone=video_backbone,
                ckpt_use_intensity=bool(ckpt_use_intensity),
                manifest_by_seq=manifest_by_seq,
                print_result=print_result,
                print_every=print_every,
                show_first_errors=show_first_errors,
            )
            correct = int(cached_run_stats["correct"])
            seen = int(cached_run_stats["seen"])
            ok_count = int(cached_run_stats["ok_count"])
            skip_count = int(cached_run_stats["skip_count"])
            err_count = int(cached_run_stats["err_count"])
            y_true_indices = list(cached_run_stats["y_true_indices"])
            y_pred_indices = list(cached_run_stats["y_pred_indices"])
            reg_true = list(cached_run_stats["reg_true"])
            reg_pred = list(cached_run_stats["reg_pred"])
            err_types = Counter(cached_run_stats["err_types"])
        else:
            # XLSX 模式：在线从原始媒体提特征，适合排查原始数据问题，
            # 但速度明显慢于 cached 模式。
            if bool(args.skip_video_encoder):
                # No OpenCV/video required.
                pass
            elif not bool(args.zero_video):
                motion_cfg = MotionConfig(num_frames=int(args.num_frames), flow_size=int(args.flow_size))
                rgb_cfg = RgbConfig(num_frames=int(args.num_frames), rgb_size=int(args.rgb_size))
            prosody_cfg = ProsodyConfig(sample_rate=int(args.sample_rate), use_pitch=(not args.prosody_no_pitch))

            it = rows
            if tqdm is not None and (not args.no_progress):
                it = tqdm(rows, total=limit, desc="Batch inference [motion_prosody]", mininterval=0.5)

            for row in it:
                if seen >= limit:
                    break

                mn_text = _fmt_text(row.get("mn", row.get("蒙文")))
                speaker_id = str(row.get("speaker_id", "UNKNOWN"))

                seq = _normalize_seq(row.get("seq", row.get("序号")))
                if not seq:
                    rec = {
                        "seq": "",
                        "status": "skip",
                        "reason": "missing_seq",
                        "label_raw": str(row.get("label_raw", row.get("情感类别", ""))).strip(),
                        "mn": mn_text,
                    }
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    skipped += 1
                    skip_count += 1
                    if print_result in {"skip", "all"}:
                        print(f"SKIP seq=<missing> reason=missing_seq label_raw={rec.get('label_raw')}")
                        if bool(args.print_text) and mn_text:
                            print(f"    mn={mn_text}")
                        sys.stdout.flush()
                    continue

                label_en = row.get("label_en") or _resolve_label_en(row)
                if not label_en:
                    rec = {
                        "seq": seq,
                        "status": "skip",
                        "reason": "unknown_label",
                        "label_raw": str(row.get("label_raw", row.get("情感类别", ""))).strip(),
                        "mn": mn_text,
                    }
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    skipped += 1
                    skip_count += 1
                    if print_result in {"skip", "all"}:
                        print(f"SKIP seq={seq} reason=unknown_label label_raw={rec.get('label_raw')}")
                        if bool(args.print_text) and mn_text:
                            print(f"    mn={mn_text}")
                        sys.stdout.flush()
                    continue

                video_path = Path(str(row["video_path"])) if row.get("video_path") else None
                audio_path = Path(str(row["audio_path"])) if row.get("audio_path") else None
                if video_path is None or audio_path is None:
                    video_path, audio_path = _paths_for_seq(data_root, label_en, seq)
                # If skipping video encoder, only audio is required.
                if bool(args.skip_video_encoder):
                    if audio_path is None:
                        rec = {
                            "seq": seq,
                            "status": "skip",
                            "reason": "missing_audio",
                            "label": label_en,
                            "audio": str(audio_path) if audio_path else None,
                            "mn": mn_text,
                        }
                        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        skipped += 1
                        skip_count += 1
                        if print_result in {"skip", "all"}:
                            print(f"SKIP seq={seq} reason=missing_audio label={label_en} audio={rec.get('audio')}")
                            if bool(args.print_text) and mn_text:
                                print(f"    mn={mn_text}")
                            sys.stdout.flush()
                        continue
                else:
                    if video_path is None or audio_path is None:
                        rec = {
                            "seq": seq,
                            "status": "skip",
                            "reason": "missing_file",
                            "label": label_en,
                            "video": str(video_path) if video_path else None,
                            "audio": str(audio_path) if audio_path else None,
                            "mn": mn_text,
                        }
                        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        skipped += 1
                        skip_count += 1
                        if print_result in {"skip", "all"}:
                            print(
                                f"SKIP seq={seq} reason=missing_file label={label_en} video={rec.get('video')} audio={rec.get('audio')}"
                            )
                            if bool(args.print_text) and mn_text:
                                print(f"    mn={mn_text}")
                            sys.stdout.flush()
                        continue

                    # Narrow types for linters/type-checkers and prevent accidental None usage.
                    assert video_path is not None
                    assert audio_path is not None

                try:
                    if stage_log:
                        video_disp = str(video_path) if video_path else "<none>"
                        audio_disp = str(audio_path) if audio_path else "<none>"
                        print(
                            f"--> [{seen + 1}/{limit}] seq={seq} label={label_en} video={video_disp} audio={audio_disp}"
                        )
                        if bool(args.print_text) and mn_text:
                            print(f"    mn={mn_text}")
                        sys.stdout.flush()
                    elif print_result in {"all"}:
                        # Lightweight start line even without stage logs
                        video_disp = str(video_path) if video_path else "<none>"
                        audio_disp = str(audio_path) if audio_path else "<none>"
                        print(f"START seq={seq} label={label_en} video={video_disp} audio={audio_disp}")
                        if bool(args.print_text) and mn_text:
                            print(f"    mn={mn_text}")
                        sys.stdout.flush()

                    t0 = time.perf_counter()
                    # 特征提取尽量留在 CPU：
                    # OpenCV / torchaudio 的 CPU 路径通常更稳，也避免 GPU 在解码阶段空转。
                    if stage_log:
                        print("    stage=video")
                        sys.stdout.flush()
                    flow = None
                    rgb = None
                    if bool(args.skip_video_encoder):
                        flow = None
                        rgb = None
                    elif bool(args.zero_video):
                        if str(video_backbone) in {"videomae", "dual"}:
                            rgb = torch.zeros(
                                (1, int(args.num_frames), 3, int(args.rgb_size), int(args.rgb_size)),
                                dtype=torch.float32,
                            )
                        if str(video_backbone) in {"flow", "dual"}:
                            flow = torch.zeros(
                                (1, 3, max(1, int(args.num_frames) - 1), int(args.flow_size), int(args.flow_size)),
                                dtype=torch.float32,
                            )
                    else:
                        assert video_path is not None
                        if str(video_backbone) == "dual":
                            flow_np, rgb_np = compute_face_flow_and_rgb_tensors(video_path, motion_cfg, rgb_cfg)
                            rgb = torch.from_numpy(rgb_np).unsqueeze(0).to(torch.float32)
                            flow = torch.from_numpy(flow_np).unsqueeze(0).to(torch.float32)
                        elif str(video_backbone) == "videomae":
                            rgb_np = compute_face_rgb_tensor(video_path, rgb_cfg)
                            rgb = torch.from_numpy(rgb_np).unsqueeze(0).to(torch.float32)
                        elif str(video_backbone) == "flow":
                            flow_np = compute_face_flow_tensor(video_path, motion_cfg)
                            flow = torch.from_numpy(flow_np).unsqueeze(0).to(torch.float32)

                    if stage_log:
                        t1 = time.perf_counter()
                        print(f"    stage=audio (after {t1 - t0:.2f}s)")
                        sys.stdout.flush()

                    wav, backend = load_audio(
                        audio_path,
                        sample_rate=int(args.sample_rate),
                        max_sec=float(args.max_audio_sec),
                        backend_mode=str(args.audio_backend),
                    )
                    wav = normalize_wav(wav, target_rms=0.1).unsqueeze(0)
                    audio_lens = torch.tensor([wav.shape[1]], dtype=torch.long)

                    if stage_log:
                        t2 = time.perf_counter()
                        print(f"    stage=prosody (backend={backend}, after {t2 - t0:.2f}s)")
                        sys.stdout.flush()
                    prosody = extract_prosody_features(wav[0], prosody_cfg).unsqueeze(0)

                    # 到这里为止都还是 CPU 侧预处理；真正前向前再统一搬到 device。
                    if stage_log:
                        t3 = time.perf_counter()
                        print(f"    stage=forward (after {t3 - t0:.2f}s)")
                        sys.stdout.flush()
                    if flow is not None:
                        flow = flow.to(device)
                    if rgb is not None:
                        rgb = rgb.to(device)
                    wav = wav.to(device)
                    audio_lens = audio_lens.to(device)
                    prosody = prosody.to(device)
                    if bool(args.zero_audio):
                        wav = torch.zeros_like(wav)
                        prosody = torch.zeros_like(prosody)

                    text_inputs = None
                    if not bool(args.zero_text):
                        text_inputs = tokenizer(
                            [str(row.get("mn", mn_text))],
                            padding=True,
                            truncation=True,
                            max_length=int(args.max_text_len),
                            return_tensors="pt",
                        )
                        text_inputs = {k: v.to(device) for k, v in text_inputs.items()}

                    logits, pred_intensity, forward_mode = _forward_outputs(
                        model,
                        flow,
                        rgb,
                        wav,
                        prosody,
                        text_inputs,
                        audio_lens,
                        None,
                        None,
                        None,
                        None,
                        device=device,
                        use_amp=use_amp,
                        amp_mod=amp_mod,
                        skip_video_encoder=bool(args.skip_video_encoder),
                        return_intensity=bool(ckpt_use_intensity),
                        video_backbone=video_backbone,
                    )

                    probs = torch.softmax(logits, dim=1)[0]
                    pred_idx = int(torch.argmax(probs).item())
                    pred = EMOTIONS[pred_idx]
                    prob = float(probs[pred_idx].item())

                    pred_intensity_val: Optional[float] = None
                    if bool(ckpt_use_intensity) and pred_intensity is not None:
                        pred_intensity_val = float(pred_intensity.detach().float()[0].item())

                    if stage_log:
                        t4 = time.perf_counter()
                        print(f"    stage=done (total {t4 - t0:.2f}s) pred={pred} p={prob:.4f}")
                        sys.stdout.flush()

                except Exception as e:
                    err_count += 1
                    err_types[type(e).__name__] += 1
                    rec = {
                        "seq": seq,
                        "status": "error",
                        "label": label_en,
                        "video": str(video_path),
                        "audio": str(audio_path),
                        "error": f"{type(e).__name__}: {e}",
                        "mn": mn_text,
                    }
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    if show_first_errors and len(first_errors) < show_first_errors:
                        msg = f"ERROR seq={seq} label={label_en} err={rec['error']}"
                        first_errors.append(msg)
                        print(msg)
                        sys.stdout.flush()
                    elif print_result in {"error", "all"}:
                        print(f"ERROR seq={seq} label={label_en} err={rec['error']}")
                        if bool(args.print_text) and mn_text:
                            print(f"    mn={mn_text}")
                        sys.stdout.flush()
                    if args.fail_fast:
                        raise
                    continue

                ok = pred == label_en
                correct += int(ok)
                y = EMOTIONS.index(label_en)
                yhat = EMOTIONS.index(pred)
                y_true_indices.append(y)
                y_pred_indices.append(yhat)
                if y == yhat:
                    tp[y] += 1
                else:
                    fp[yhat] += 1
                    fn[y] += 1
                seen += 1
                ok_count += 1

                gt_intensity_val = _parse_intensity(row.get("intensity", row.get("_intensity", row.get("情感强度"))))
                if bool(ckpt_use_intensity) and (pred_intensity_val is not None) and (gt_intensity_val is not None):
                    reg_pred.append(float(pred_intensity_val))
                    reg_true.append(float(gt_intensity_val))

                rec = {
                    "seq": seq,
                    "status": "ok",
                    "label": label_en,
                    "pred": pred,
                    "match": bool(ok),
                    "probability": prob,
                    "audio_backend": backend,
                    "speaker_id": speaker_id,
                    "video_mode": (
                        "skip_encoder"
                        if bool(args.skip_video_encoder)
                        else ("zero" if bool(args.zero_video) else "opencv")
                    ),
                    "video": str(video_path) if video_path else None,
                    "audio": str(audio_path),
                    "mn": mn_text,
                }
                if bool(ckpt_use_intensity):
                    rec["pred_intensity"] = pred_intensity_val
                    rec["intensity_gt"] = gt_intensity_val
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")

                if print_result in {"ok", "all"}:
                    tag = "OK" if ok else "MISS"
                    print(f"{tag} seq={seq} label={label_en} pred={pred} p={prob:.4f} backend={backend}")
                    if bool(args.print_text) and mn_text:
                        print(f"    mn={mn_text}")
                    sys.stdout.flush()

                should_print = False
                if args.debug:
                    should_print = True
                elif print_every > 0 and (seen % print_every) == 0:
                    should_print = True

                if should_print:
                    acc = correct / max(1, seen)
                    msg = (
                        f"[{seen}/{limit}] acc={acc:.4f} seq={seq} label={label_en} pred={pred} "
                        f"p={prob:.4f} backend={backend}"
                    )
                    print(msg)
                    if args.print_json:
                        print(json.dumps(rec, ensure_ascii=False))

                # Ensure tqdm advances even on slower terminals.
                if tqdm is not None and hasattr(it, "update"):
                    try:
                        it.update(0)  # type: ignore[call-arg]
                    except Exception:
                        pass

    acc = correct / max(1, seen)
    class_summary = classification_summary(y_true_indices, y_pred_indices, EMOTIONS)
    mse = None
    mae = None
    ccc = None
    if reg_true and reg_pred:
        rt = torch.tensor(reg_true, dtype=torch.float32)
        rp = torch.tensor(reg_pred, dtype=torch.float32)
        diff = (rp - rt).to(torch.float64)
        mse = float((diff * diff).mean().item())
        mae = float(diff.abs().mean().item())
        ccc = _ccc(rp, rt)
    speaker_baseline = None
    if manifest is not None and args.subset in {"train", "val"}:
        train_items = select_manifest_items(manifest, "train")
        eval_items = select_manifest_items(manifest, args.subset)
        speaker_baseline = speaker_majority_baseline(train_items, eval_items, EMOTIONS)

    metrics_summary = {
        "xlsx": str(xlsx) if cached_input is None and split_manifest_path is None else None,
        "cached_dataset": str(cached_input) if cached_input is not None else None,
        "feature_cache": str(feature_cache) if feature_cache is not None else None,
        "split_manifest": str(split_manifest_path) if split_manifest_path is not None else None,
        "subset": str(args.subset),
        "benchmark_tag": str(args.benchmark_tag),
        "ablation": str(args.ablation),
        "zero_video": bool(args.zero_video),
        "zero_audio": bool(args.zero_audio),
        "zero_text": bool(args.zero_text),
        "checkpoint": str(ckpt_path),
        "output": str(out_path),
        "attempted": int(ok_count + err_count),
        "ok": int(ok_count),
        "errors": int(err_count),
        "skipped": int(skip_count),
        "accuracy_on_ok": float(acc),
        "macro_f1_on_ok": float(class_summary.get("macro_f1", 0.0)),
        "per_class_recall": class_summary.get("per_class_recall", {}),
        "confusion_matrix": class_summary.get("confusion_matrix", []),
        "support": class_summary.get("support", {}),
        "pred_counts": class_summary.get("pred_counts", {}),
        "intensity_enabled": bool(ckpt_use_intensity),
        "intensity_n": int(len(reg_true)),
        "intensity_mse": mse,
        "intensity_mae": mae,
        "intensity_ccc": ccc,
        "device": str(device),
        "runtime_profile": profile.to_jsonable(),
        "amp_mode": resolved_amp_mode,
        "amp": bool(use_amp),
        "error_types": dict(err_types),
        "manifest_sha256": manifest_hash,
    }
    if manifest is not None:
        metrics_summary["manifest_summary"] = manifest.get("summary", {})
    if speaker_baseline is not None:
        metrics_summary["speaker_majority_baseline"] = speaker_baseline

    metrics_path = out_path.with_suffix(".metrics.json")
    metrics_path.write_text(json.dumps(metrics_summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(metrics_summary, ensure_ascii=False, indent=2))
    print(f"Wrote metrics -> {metrics_path}")

    if err_types:
        top = err_types.most_common(8)
        print("Top error types:")
        for k, v in top:
            print(f"  - {k}: {v}")


if __name__ == "__main__":
    try:
        torch.set_float32_matmul_precision("high")
    except Exception:
        pass
    main()
