from __future__ import annotations

import argparse
import json
import sys
import contextlib
import os
import math
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader, Subset
from tqdm import tqdm


# HuggingFace tokenizers may warn when DataLoader workers fork after tokenizers were used.
# Disabling tokenizers parallelism avoids deadlock risk and removes noisy warnings.
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")


def _ensure_project_root_on_path() -> None:
    """在脚本直跑时确保仓库根目录可导入。"""

    # When running as: python3 train_motion_audio.py
    # sys.path[0] is already the repo root, but keeping it explicit makes
    # direct execution and legacy-compat imports behave the same way.
    project_root = Path(__file__).resolve().parent
    project_root_str = str(project_root)
    if project_root_str not in sys.path:
        sys.path.insert(0, project_root_str)


_ensure_project_root_on_path()

from audio_aug import AudioAugConfig, augment_wav
from audio_aug import normalize_wav
from data import CachedMotionAudioDataset, collate
from manifest_utils import EMOTIONS, load_split_manifest, manifest_sha256, select_manifest_items
from metrics_utils import classification_summary, speaker_majority_baseline
from models import FusionClassifier
from prosody import ProsodyConfig, extract_prosody_features


def parse_args():
    """定义训练入口的全部命令行参数。"""

    p = argparse.ArgumentParser(description="Train motion(flow)/rgb + audio + prosody fusion on cached dataset")
    p.add_argument("--cached-dataset", type=Path, required=True)
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--num-workers", type=int, default=2)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--output-dir", type=Path, default=Path("outputs/motion_prosody"))
    p.add_argument("--split-manifest", type=Path, default=None, help="Optional split manifest generated by build_split_manifest.py")
    p.add_argument("--benchmark-tag", type=str, default="default", help="Free-form benchmark name recorded in metrics/checkpoint metadata")
    p.add_argument("--freeze-audio", action="store_true")
    p.add_argument("--freeze-video", action="store_true", help="Freeze the video encoder")
    p.add_argument("--freeze-flow", action="store_true", help="Freeze only the optical-flow branch")
    p.add_argument("--freeze-rgb", action="store_true", help="Freeze only the RGB VideoMAE branch")
    p.add_argument("--freeze-prosody", action="store_true", help="Freeze the prosody MLP")

    # Video backbone
    p.add_argument(
        "--video-backbone",
        type=str,
        default="dual",
        choices=["flow", "videomae", "dual"],
        help="Video branch: optical-flow Conv3D, VideoMAE RGB backbone, or dual (flow+rgb)",
    )
    p.add_argument(
        "--video-model",
        type=str,
        default="MCG-NJU/videomae-large",
        help="HF model name for VideoMAE backbone (used when --video-backbone=videomae)",
    )

    # Audio backbone
    p.add_argument(
        "--audio-model",
        type=str,
        default="microsoft/wavlm-large",
        help="HF model name for audio encoder (use 'wav2vec2_base' for torchaudio wav2vec2)",
    )

    # Fusion settings
    p.add_argument(
        "--fusion-mode",
        type=str,
        default="gated_text",
        choices=["gated_text", "concat"],
        help="Fusion strategy: gated_text (default) or concat",
    )
    p.add_argument(
        "--gate-temperature",
        type=float,
        default=1.0,
        help="Gate temperature (>0). Lower => sharper gating, higher => smoother",
    )
    p.add_argument(
        "--gate-scale",
        type=float,
        default=1.0,
        help="Scale factor applied to the gate (controls contribution strength)",
    )
    p.add_argument(
        "--delta-scale",
        type=float,
        default=1.0,
        help="Scale factor applied to the delta (controls update magnitude)",
    )
    p.add_argument(
        "--modality-dropout",
        type=float,
        default=0.1,
        help="Randomly drop non-text modalities during training for robustness",
    )

    # Text branch (Mongolian)
    p.add_argument(
        "--text-model",
        type=str,
        default="xlm-roberta-large",
        help="HF model name for text encoder",
    )
    p.add_argument("--freeze-text", action="store_true", help="Freeze the text (mBERT) encoder")
    p.add_argument(
        "--max-text-len",
        type=int,
        default=128,
        help="Tokenizer max_length for Mongolian text (truncation enabled)",
    )
    p.add_argument("--audio-aug", action="store_true")
    p.set_defaults(recompute_prosody_on_aug=True)
    p.add_argument(
        "--no-recompute-prosody-on-aug",
        dest="recompute_prosody_on_aug",
        action="store_false",
        help="When using --audio-aug, keep cached prosody vectors instead of recomputing from augmented wav",
    )
    p.add_argument(
        "--prosody-no-pitch",
        action="store_true",
        help="Disable pitch extraction (energy-only prosody; faster, less informative)",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--train-split", type=float, default=0.8)
    p.add_argument(
        "--split-mode",
        type=str,
        default="random",
        choices=["random", "sequential"],
        help="How to split train/val. 'random' is deterministic given --seed; 'sequential' keeps original order.",
    )
    p.add_argument("--zero-video", action="store_true", help="Zero video inputs for training/eval ablations")
    p.add_argument("--zero-audio", action="store_true", help="Zero audio-derived inputs (wav/audio_emb + prosody) for ablations")
    p.add_argument("--zero-text", action="store_true", help="Drop the text branch for training/eval ablations")
    p.add_argument(
        "--ablation",
        type=str,
        default="full",
        choices=["full", "text-only", "audio-only", "video-only", "no-text", "no-audio", "no-video"],
        help="Convenience preset for common modality ablations",
    )

    # Performance knobs (especially useful on CUDA).
    p.add_argument(
        "--pin-memory",
        action="store_true",
        help="Use DataLoader pin_memory for faster H2D copies (recommended on CUDA)",
    )
    p.add_argument(
        "--persistent-workers",
        action="store_true",
        help="Keep DataLoader workers alive across epochs (recommended when num-workers>0)",
    )
    p.add_argument(
        "--prefetch-factor",
        type=int,
        default=2,
        help="DataLoader prefetch_factor (only used when num-workers>0)",
    )
    p.add_argument(
        "--amp",
        action="store_true",
        help="Enable CUDA AMP mixed precision for faster training",
    )

    # Optional intensity regression (continuous label).
    p.add_argument(
        "--use-intensity",
        action="store_true",
        help=(
            "Enable auxiliary emotion intensity regression head and metrics. "
            "Requires cached samples to contain a finite 'intensity' value (else it is masked)."
        ),
    )
    p.add_argument(
        "--intensity-loss",
        type=str,
        default="mse",
        choices=["mse", "mae"],
        help="Regression loss type when --use-intensity is enabled",
    )
    p.add_argument(
        "--intensity-weight",
        type=float,
        default=1.0,
        help="Weight for regression loss in total loss: loss = CE + w * reg",
    )
    return p.parse_args()


def set_seed(seed: int):
    """固定 Python / NumPy / PyTorch 随机种子。"""

    import random
    import numpy as np

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _resolve_ablation_flags(args: argparse.Namespace) -> tuple[bool, bool, bool]:
    """把 `--ablation` 预设和显式 zero-* 标志合并成最终消融开关。"""

    ablation = str(getattr(args, "ablation", "full") or "full").strip().lower()
    zero_video = bool(getattr(args, "zero_video", False))
    zero_audio = bool(getattr(args, "zero_audio", False))
    zero_text = bool(getattr(args, "zero_text", False))
    presets = {
        "full": (False, False, False),
        "text-only": (True, True, False),
        "audio-only": (True, False, True),
        "video-only": (False, True, True),
        "no-text": (False, False, True),
        "no-audio": (False, True, False),
        "no-video": (True, False, False),
    }
    preset = presets.get(ablation)
    if preset is not None:
        zero_video = zero_video or preset[0]
        zero_audio = zero_audio or preset[1]
        zero_text = zero_text or preset[2]
    return zero_video, zero_audio, zero_text


def _macro_f1(y_true: torch.Tensor, y_pred: torch.Tensor, num_classes: int) -> float:
    """从标签张量直接计算 macro-F1。"""

    # y_true/y_pred: (N,) int64
    if y_true.numel() == 0:
        return 0.0
    y_true = y_true.to(torch.long)
    y_pred = y_pred.to(torch.long)

    f1_sum = 0.0
    for c in range(int(num_classes)):
        tp = int(((y_true == c) & (y_pred == c)).sum().item())
        fp = int(((y_true != c) & (y_pred == c)).sum().item())
        fn = int(((y_true == c) & (y_pred != c)).sum().item())
        denom = (2 * tp + fp + fn)
        f1_c = (2 * tp / denom) if denom > 0 else 0.0
        f1_sum += float(f1_c)
    return float(f1_sum / max(1, int(num_classes)))


def _ccc(x: torch.Tensor, y: torch.Tensor) -> float:
    """计算 Concordance Correlation Coefficient。

    公式为：
    `CCC = 2 * cov(x, y) / (var(x) + var(y) + (mean_x - mean_y)^2)`。

    它同时惩罚：
    - 相关性差；
    - 均值偏移；
    - 方差不一致。

    因此比单纯的 Pearson 更适合连续强度回归评估。
    """
    x = x.flatten().to(torch.float64)
    y = y.flatten().to(torch.float64)
    n = int(x.numel())
    if n < 2:
        return 0.0
    mx = float(x.mean().item())
    my = float(y.mean().item())
    vx = float(x.var(unbiased=False).item())
    vy = float(y.var(unbiased=False).item())
    cov = float(((x - mx) * (y - my)).mean().item())
    denom = vx + vy + (mx - my) ** 2
    if denom <= 0:
        return 0.0
    return float((2.0 * cov) / denom)


def _to_jsonable(value: Any) -> Any:
    """把 Path/tuple 等对象递归转换成可写入 JSON 的结构。"""

    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(k): _to_jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_jsonable(v) for v in value]
    return value


def _save_metrics_and_plots(out_dir: Path, metrics: dict[str, Any]) -> None:
    """落盘训练指标，并尽量生成准确率/损失曲线图。"""

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")

    # Plot (optional). If matplotlib isn't installed, we still keep metrics.json.
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:
        print(f"Plot skipped (matplotlib not available): {type(e).__name__}: {e}")
        print("Install with: pip install matplotlib")
        return

    epochs = list(range(1, len(metrics.get("train_loss", [])) + 1))
    if not epochs:
        return

    # Accuracy plot
    plt.figure(figsize=(8, 4.5))
    if "train_acc" in metrics:
        plt.plot(epochs, metrics["train_acc"], label="train")
    if "val_acc" in metrics:
        plt.plot(epochs, metrics["val_acc"], label="val")
    plt.xlabel("epoch")
    plt.ylabel("accuracy")
    plt.title("Accuracy vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "accuracy_curve.png", dpi=160)
    plt.close()

    # Loss plot
    plt.figure(figsize=(8, 4.5))
    if "train_loss" in metrics:
        plt.plot(epochs, metrics["train_loss"], label="train")
    if "val_loss" in metrics:
        plt.plot(epochs, metrics["val_loss"], label="val")
    plt.xlabel("epoch")
    plt.ylabel("loss")
    plt.title("Loss vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "loss_curve.png", dpi=160)
    plt.close()


def _print_split_label_hist(name: str, ds: CachedMotionAudioDataset, indices: list[int], num_classes: int = 7) -> None:
    """打印某个子集的标签直方图，便于快速检查切分是否异常。"""

    counts = torch.zeros(num_classes, dtype=torch.long)
    oob: list[tuple[int, int]] = []
    for i in indices:
        y = ds.samples[i].get("label", None)
        if isinstance(y, torch.Tensor):
            y_int = int(y.item())
        else:
            if y is None:
                oob.append((i, -1))
                continue
            y_int = int(y)
        if 0 <= y_int < num_classes:
            counts[y_int] += 1
        else:
            oob.append((i, y_int))
    total = int(counts.sum().item())
    parts = [f"{k}:{int(v)}" for k, v in enumerate(counts.tolist())]
    print(f"{name} label histogram (n={total}): " + " ".join(parts))
    if oob:
        shown = ", ".join([f"idx={i}/label={y}" for i, y in oob[:10]])
        print(f"WARNING: {name} has out-of-range labels (show up to 10): {shown}")


def main():
    """训练主流程。

    这部分串起了主工程的完整训练链路：
    1. 读取缓存 shard；
    2. 根据 manifest 或随机策略切分 train/val；
    3. 构造 tokenizer、模型、优化器与 AMP；
    4. 逐 epoch 进行训练与验证；
    5. 保存最佳 checkpoint 和完整指标。
    """

    args = parse_args()
    set_seed(args.seed)
    zero_video, zero_audio, zero_text = _resolve_ablation_flags(args)
    args.zero_video = zero_video
    args.zero_audio = zero_audio
    args.zero_text = zero_text

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type == "cuda":
        try:
            name = torch.cuda.get_device_name(0)
            print(f"Using device: cuda (0) - {name}")
        except Exception:
            print("Using device: cuda")
    else:
        print(f"Using device: {device}")

    # GPU perf hints
    if device.type == "cuda":
        try:
            torch.backends.cudnn.benchmark = True
        except Exception:
            pass
        try:
            torch.set_float32_matmul_precision("high")
        except Exception:
            pass

    # Print cached shard paths (helps debug loading and ensures reproducibility).
    cached_dir = args.cached_dataset.expanduser()
    if args.split_manifest is not None and not args.split_manifest.expanduser().exists():
        raise FileNotFoundError(f"Split manifest not found: {args.split_manifest.expanduser()}")
    if cached_dir.is_file():
        shard_paths = [cached_dir]
    else:
        shard_paths = sorted(
            cached_dir.glob("*.pt"),
            key=lambda p: int(p.stem) if p.stem.isdigit() else p.stem,
        )
    print(f"Cached dataset path: {cached_dir}")
    print(f"Found {len(shard_paths)} shard(s):")
    for p in shard_paths:
        print(f"  - {p}")

    ds = CachedMotionAudioDataset(args.cached_dataset)
    split_manifest = None
    manifest_hash = None
    train_manifest_items: list[dict[str, Any]] = []
    val_manifest_items: list[dict[str, Any]] = []

    if args.split_manifest is not None:
        split_manifest = load_split_manifest(args.split_manifest.expanduser())
        manifest_hash = manifest_sha256(args.split_manifest.expanduser())
        train_manifest_items = select_manifest_items(split_manifest, "train")
        val_manifest_items = select_manifest_items(split_manifest, "val")

        stem_to_index: dict[str, int] = {}
        duplicate_stems: set[str] = set()
        for idx, sample in enumerate(ds.samples):
            stem = str(sample.get("stem", idx))
            if stem in stem_to_index:
                duplicate_stems.add(stem)
                continue
            stem_to_index[stem] = idx
        if duplicate_stems:
            shown = ", ".join(sorted(list(duplicate_stems))[:10])
            print(f"WARNING: duplicate stems in cached dataset; first occurrence will be used. Example(s): {shown}")

        def _indices_for_manifest(items: list[dict[str, Any]], name: str) -> list[int]:
            """把 manifest 中的样本序号映射成缓存数据集索引。"""

            indices: list[int] = []
            missing_stems: list[str] = []
            for item in items:
                stem = str(item.get("seq", ""))
                if stem in stem_to_index:
                    indices.append(stem_to_index[stem])
                else:
                    missing_stems.append(stem)
            if missing_stems:
                preview = ", ".join(missing_stems[:10])
                raise RuntimeError(f"{name} split manifest contains stems missing from cache: {preview}")
            return indices

        train_indices = _indices_for_manifest(train_manifest_items, "train")
        val_indices = _indices_for_manifest(val_manifest_items, "val")
        if not train_indices or not val_indices:
            raise RuntimeError("Split manifest produced an empty train or val subset.")
        print(f"Using split manifest: {args.split_manifest.expanduser()}")
        print(f"Manifest sha256: {manifest_hash}")
    else:
        # deterministic split
        n = len(ds)
        n_train = int(n * args.train_split)
        if args.split_mode == "random":
            g = torch.Generator()
            g.manual_seed(int(args.seed))
            indices = torch.randperm(n, generator=g).tolist()
        else:
            indices = list(range(n))
        train_indices = indices[:n_train]
        val_indices = indices[n_train:]
    train_ds = Subset(ds, train_indices)
    val_ds = Subset(ds, val_indices)
    _print_split_label_hist("train", ds, train_indices, num_classes=7)
    _print_split_label_hist("val", ds, val_indices, num_classes=7)
    speaker_baseline = None
    if split_manifest is not None and train_manifest_items and val_manifest_items:
        speaker_baseline = speaker_majority_baseline(train_manifest_items, val_manifest_items, EMOTIONS)

    pin_memory = bool(args.pin_memory) if device.type == "cuda" else False
    persistent_workers = bool(args.persistent_workers) if int(args.num_workers) > 0 else False
    prefetch_factor = int(args.prefetch_factor)
    dl_kwargs = {
        "num_workers": int(args.num_workers),
        "collate_fn": collate,
        "pin_memory": pin_memory,
    }
    if int(args.num_workers) > 0:
        dl_kwargs["persistent_workers"] = persistent_workers
        dl_kwargs["prefetch_factor"] = max(1, prefetch_factor)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, **dl_kwargs)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, **dl_kwargs)

    try:
        from transformers import AutoTokenizer
    except Exception as e:
        raise RuntimeError(
            "transformers is required for tri-modal training (text branch). Install with: pip install transformers"
        ) from e

    tokenizer = AutoTokenizer.from_pretrained(str(args.text_model))

    model = FusionClassifier(
        num_classes=7,
        freeze_audio=args.freeze_audio,
        freeze_video=bool(args.freeze_video),
        freeze_flow=bool(args.freeze_video or args.freeze_flow),
        freeze_rgb=bool(args.freeze_video or args.freeze_rgb),
        freeze_prosody=bool(args.freeze_prosody),
        text_model=str(args.text_model),
        freeze_text=bool(args.freeze_text),
        audio_model=str(args.audio_model),
        video_backbone=str(args.video_backbone),
        video_model=str(args.video_model),
        fusion_mode=str(args.fusion_mode),
        modality_dropout=float(args.modality_dropout),
        gate_temperature=float(args.gate_temperature),
        gate_scale=float(args.gate_scale),
        delta_scale=float(args.delta_scale),
    ).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    loss_fn = torch.nn.CrossEntropyLoss()

    aug_cfg = AudioAugConfig(sample_rate=int(ds.config.get("sample_rate", 24000)))
    prosody_cfg = ProsodyConfig(sample_rate=aug_cfg.sample_rate, use_pitch=(not args.prosody_no_pitch))

    use_amp = bool(args.amp) and device.type == "cuda"
    amp_mod = getattr(torch, "amp", None)
    if amp_mod is not None and hasattr(amp_mod, "GradScaler"):
        try:
            scaler = amp_mod.GradScaler("cuda", enabled=use_amp)  # type: ignore[attr-defined]
        except Exception:
            scaler = torch.cuda.amp.GradScaler(enabled=use_amp)
    else:
        scaler = torch.cuda.amp.GradScaler(enabled=use_amp)

    best_acc = 0.0
    best_epoch = 0
    best_val_summary: dict[str, Any] = {}
    best_train_summary: dict[str, Any] = {}
    out_dir = args.output_dir.expanduser()
    (out_dir / "checkpoints").mkdir(parents=True, exist_ok=True)

    history: dict[str, list[float]] = {
        "train_loss": [],
        "train_acc": [],
        "train_f1": [],
        "val_loss": [],
        "val_acc": [],
        "val_f1": [],
    }

    if bool(args.use_intensity):
        history.update(
            {
                "train_mse": [],
                "train_mae": [],
                "train_ccc": [],
                "train_intensity_n": [],
                "val_mse": [],
                "val_mae": [],
                "val_ccc": [],
                "val_intensity_n": [],
            }
        )

    warned_audio_aug_ignored = False

    for epoch in range(1, args.epochs + 1):
        model.train()
        total = 0
        correct = 0
        running = 0.0
        y_true_all: list[torch.Tensor] = []
        y_pred_all: list[torch.Tensor] = []

        reg_pred_all: list[torch.Tensor] = []
        reg_true_all: list[torch.Tensor] = []
        for batch in tqdm(train_loader, desc=f"Epoch {epoch}/{args.epochs} [train]"):
            nb = pin_memory and device.type == "cuda"

            audio_emb = batch.get("audio_emb", None)
            has_audio = "audio" in batch

            # Keep audio augmentation on CPU to avoid costly per-sample CPU<->GPU transfers
            # (and to avoid torchaudio CUDA resample instability).
            prosody_cpu = batch["prosody"]
            y = batch["labels"].to(device, non_blocking=nb)

            if audio_emb is not None:
                # 已缓存 audio_emb 时，训练阶段不再重新跑 WavLM。
                # 这时 `--audio-aug` 无法作用到 embedding，因此只能提示并忽略。
                if args.audio_aug and not warned_audio_aug_ignored:
                    print("WARNING: audio_emb detected; --audio-aug is ignored for cached embeddings.")
                    warned_audio_aug_ignored = True
                if has_audio:
                    wav_cpu = batch["audio"]
                else:
                    wav_cpu = torch.zeros((prosody_cpu.shape[0], 1), dtype=torch.float32)
                audio_lens = batch.get("audio_lens", None)
            else:
                if not has_audio:
                    raise RuntimeError("Batch is missing 'audio' and no 'audio_emb' provided. Re-run predecode with --audio-repr raw or wavlm.")
                wav_cpu = batch["audio"]
                # 先做基础 RMS 归一化，再做可选增强，最后再归一化一次，
                # 避免增强后的幅值漂移把编码器输入尺度拉乱。
                wav_cpu = normalize_wav(wav_cpu, target_rms=0.1)
                if args.audio_aug:
                    wav_cpu = augment_wav(wav_cpu, aug_cfg)
                    wav_cpu = normalize_wav(wav_cpu, target_rms=0.1)
                    if args.recompute_prosody_on_aug:
                        # 韵律来自增强后的波形时，prosody 才与模型实际看到的音频一致。
                        prosody_list = [extract_prosody_features(wav_cpu[i].detach(), prosody_cfg) for i in range(wav_cpu.shape[0])]
                        prosody_cpu = torch.stack(prosody_list, dim=0)
                audio_lens = batch["audio_lens"]

            if str(args.video_backbone) == "videomae":
                if "rgb" not in batch:
                    raise RuntimeError("Batch is missing 'rgb'. Re-run predecode with --video-repr rgb or both.")
                flow = None
                rgb = batch["rgb"].to(device, non_blocking=nb)
            elif str(args.video_backbone) == "dual":
                if "flow" not in batch or "rgb" not in batch:
                    raise RuntimeError("Batch must contain both 'flow' and 'rgb'. Re-run predecode with --video-repr both.")
                flow = batch["flow"].to(device, non_blocking=nb)
                rgb = batch["rgb"].to(device, non_blocking=nb)
            else:
                if "flow" not in batch:
                    raise RuntimeError("Batch is missing 'flow'. Re-run predecode with --video-repr flow or both.")
                flow = batch["flow"].to(device, non_blocking=nb)
                rgb = None

            wav = wav_cpu.to(device, non_blocking=nb)
            audio_lens_t = audio_lens.to(device, non_blocking=nb) if audio_lens is not None else None
            prosody = prosody_cpu.to(device, non_blocking=nb)
            audio_emb_t = audio_emb.to(device, non_blocking=nb) if audio_emb is not None else None
            if bool(args.zero_video):
                if flow is not None:
                    flow = torch.zeros_like(flow)
                if rgb is not None:
                    rgb = torch.zeros_like(rgb)
            if bool(args.zero_audio):
                wav = torch.zeros_like(wav)
                prosody = torch.zeros_like(prosody)
                if audio_emb_t is not None:
                    audio_emb_t = torch.zeros_like(audio_emb_t)

            mn_list = batch.get("mn", None)
            if mn_list is None:
                raise RuntimeError("Batch is missing 'mn'. Please re-run predecode with mn saved.")
            text_inputs = None
            if not bool(args.zero_text):
                text_inputs = tokenizer(
                    [str(x) for x in mn_list],
                    padding=True,
                    truncation=True,
                    max_length=int(args.max_text_len),
                    return_tensors="pt",
                )
                text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}

            opt.zero_grad(set_to_none=True)
            if device.type == "cuda":
                amp_mod = getattr(torch, "amp", None)
                if amp_mod is not None and hasattr(amp_mod, "autocast"):
                    amp_ctx = amp_mod.autocast("cuda", enabled=use_amp)  # type: ignore[attr-defined]
                else:
                    amp_ctx = torch.cuda.amp.autocast(enabled=use_amp)
            else:
                amp_ctx = contextlib.nullcontext()

            with amp_ctx:
                if bool(args.use_intensity):
                    logits, pred_intensity = model(
                        flow,
                        wav,
                        prosody,
                        text_inputs=text_inputs,
                        return_intensity=True,
                        rgb=rgb,
                        audio_lens=audio_lens_t,
                        audio_emb=audio_emb_t,
                    )
                else:
                    logits = model(
                        flow,
                        wav,
                        prosody,
                        text_inputs=text_inputs,
                        rgb=rgb,
                        audio_lens=audio_lens_t,
                        audio_emb=audio_emb_t,
                    )

                # 主任务始终是情绪分类交叉熵。
                loss = loss_fn(logits, y)

                if bool(args.use_intensity):
                    gt_intensity = batch["intensity"].to(device, non_blocking=nb).to(torch.float32)
                    intensity_mask = batch["intensity_mask"].to(device, non_blocking=nb)
                    if intensity_mask.any():
                        pred_f = pred_intensity.to(torch.float32)[intensity_mask]
                        gt_f = gt_intensity[intensity_mask]
                        if str(args.intensity_loss).lower().strip() == "mae":
                            reg_loss = torch.abs(pred_f - gt_f).mean()
                        else:
                            reg_loss = torch.square(pred_f - gt_f).mean()
                        # 多任务总损失：
                        #   total_loss = CE + intensity_weight * reg_loss
                        # 其中 reg_loss 是 MSE 或 MAE。
                        loss = loss + float(args.intensity_weight) * reg_loss

            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()

            running += loss.item() * y.size(0)
            pred = logits.argmax(dim=1)
            correct += (pred == y).sum().item()
            total += y.size(0)

            y_true_all.append(y.detach().cpu())
            y_pred_all.append(pred.detach().cpu())

            if bool(args.use_intensity):
                gt_intensity_cpu = batch["intensity"].detach().cpu().to(torch.float32)
                mask_cpu = batch["intensity_mask"].detach().cpu()
                pred_intensity_cpu = pred_intensity.detach().cpu().to(torch.float32)
                if bool(mask_cpu.any()):
                    reg_true_all.append(gt_intensity_cpu[mask_cpu])
                    reg_pred_all.append(pred_intensity_cpu[mask_cpu])

        train_loss = running / max(1, total)
        train_acc = correct / max(1, total)

        yt = torch.cat(y_true_all, dim=0) if y_true_all else torch.empty((0,), dtype=torch.long)
        yp = torch.cat(y_pred_all, dim=0) if y_pred_all else torch.empty((0,), dtype=torch.long)
        train_class_summary = classification_summary(yt.tolist(), yp.tolist(), EMOTIONS)
        train_f1 = float(train_class_summary.get("macro_f1", 0.0))

        train_mse = 0.0
        train_mae = 0.0
        train_ccc = 0.0
        train_intensity_n = 0
        if bool(args.use_intensity) and reg_true_all and reg_pred_all:
            rt = torch.cat(reg_true_all, dim=0).to(torch.float32)
            rp = torch.cat(reg_pred_all, dim=0).to(torch.float32)
            train_intensity_n = int(rt.numel())
            if train_intensity_n > 0:
                diff = (rp - rt).to(torch.float64)
                train_mse = float((diff * diff).mean().item())
                train_mae = float(diff.abs().mean().item())
                train_ccc = _ccc(rp, rt)

        model.eval()
        v_total = 0
        v_correct = 0
        v_loss_sum = 0.0
        v_y_true_all: list[torch.Tensor] = []
        v_y_pred_all: list[torch.Tensor] = []
        v_reg_pred_all: list[torch.Tensor] = []
        v_reg_true_all: list[torch.Tensor] = []
        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f"Epoch {epoch}/{args.epochs} [val]"):
                nb = pin_memory and device.type == "cuda"
                if str(args.video_backbone) == "videomae":
                    if "rgb" not in batch:
                        raise RuntimeError("Batch is missing 'rgb'. Re-run predecode with --video-repr rgb or both.")
                    flow = None
                    rgb = batch["rgb"].to(device, non_blocking=nb)
                elif str(args.video_backbone) == "dual":
                    if "flow" not in batch or "rgb" not in batch:
                        raise RuntimeError("Batch must contain both 'flow' and 'rgb'. Re-run predecode with --video-repr both.")
                    flow = batch["flow"].to(device, non_blocking=nb)
                    rgb = batch["rgb"].to(device, non_blocking=nb)
                else:
                    if "flow" not in batch:
                        raise RuntimeError("Batch is missing 'flow'. Re-run predecode with --video-repr flow or both.")
                    flow = batch["flow"].to(device, non_blocking=nb)
                    rgb = None

                audio_emb = batch.get("audio_emb", None)
                has_audio = "audio" in batch
                if audio_emb is not None:
                    if has_audio:
                        wav = normalize_wav(batch["audio"], target_rms=0.1).to(device, non_blocking=nb)
                        audio_lens = batch.get("audio_lens", None)
                    else:
                        wav = torch.zeros((batch["labels"].shape[0], 1), device=device, dtype=torch.float32)
                        audio_lens = None
                else:
                    if not has_audio:
                        raise RuntimeError("Batch is missing 'audio' and no 'audio_emb' provided. Re-run predecode with --audio-repr raw or wavlm.")
                    wav = normalize_wav(batch["audio"], target_rms=0.1).to(device, non_blocking=nb)
                    audio_lens = batch["audio_lens"].to(device, non_blocking=nb)
                audio_lens_t = audio_lens.to(device, non_blocking=nb) if audio_lens is not None else None
                audio_emb_t = audio_emb.to(device, non_blocking=nb) if audio_emb is not None else None
                prosody = batch["prosody"].to(device, non_blocking=nb)
                y = batch["labels"].to(device, non_blocking=nb)
                if bool(args.zero_video):
                    if flow is not None:
                        flow = torch.zeros_like(flow)
                    if rgb is not None:
                        rgb = torch.zeros_like(rgb)
                if bool(args.zero_audio):
                    wav = torch.zeros_like(wav)
                    prosody = torch.zeros_like(prosody)
                    if audio_emb_t is not None:
                        audio_emb_t = torch.zeros_like(audio_emb_t)

                mn_list = batch.get("mn", None)
                if mn_list is None:
                    raise RuntimeError("Batch is missing 'mn'. Please re-run predecode with mn saved.")
                text_inputs = None
                if not bool(args.zero_text):
                    text_inputs = tokenizer(
                        [str(x) for x in mn_list],
                        padding=True,
                        truncation=True,
                        max_length=int(args.max_text_len),
                        return_tensors="pt",
                    )
                    text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}

                if device.type == "cuda":
                    amp_mod = getattr(torch, "amp", None)
                    if amp_mod is not None and hasattr(amp_mod, "autocast"):
                        amp_ctx = amp_mod.autocast("cuda", enabled=use_amp)  # type: ignore[attr-defined]
                    else:
                        amp_ctx = torch.cuda.amp.autocast(enabled=use_amp)
                else:
                    amp_ctx = contextlib.nullcontext()

                with amp_ctx:
                    if bool(args.use_intensity):
                        logits, pred_intensity = model(
                            flow,
                            wav,
                            prosody,
                            text_inputs=text_inputs,
                            return_intensity=True,
                            rgb=rgb,
                            audio_lens=audio_lens_t,
                            audio_emb=audio_emb_t,
                        )
                    else:
                        logits = model(
                            flow,
                            wav,
                            prosody,
                            text_inputs=text_inputs,
                            rgb=rgb,
                            audio_lens=audio_lens_t,
                            audio_emb=audio_emb_t,
                        )

                    loss = loss_fn(logits, y)

                    if bool(args.use_intensity):
                        gt_intensity = batch["intensity"].to(device, non_blocking=nb).to(torch.float32)
                        intensity_mask = batch["intensity_mask"].to(device, non_blocking=nb)
                        if intensity_mask.any():
                            pred_f = pred_intensity.to(torch.float32)[intensity_mask]
                            gt_f = gt_intensity[intensity_mask]
                            if str(args.intensity_loss).lower().strip() == "mae":
                                reg_loss = torch.abs(pred_f - gt_f).mean()
                            else:
                                reg_loss = torch.square(pred_f - gt_f).mean()
                            loss = loss + float(args.intensity_weight) * reg_loss
                v_loss_sum += loss.item() * y.size(0)
                pred = logits.argmax(dim=1)
                v_correct += (pred == y).sum().item()
                v_total += y.size(0)

                v_y_true_all.append(y.detach().cpu())
                v_y_pred_all.append(pred.detach().cpu())
                if bool(args.use_intensity):
                    gt_intensity_cpu = batch["intensity"].detach().cpu().to(torch.float32)
                    mask_cpu = batch["intensity_mask"].detach().cpu()
                    pred_intensity_cpu = pred_intensity.detach().cpu().to(torch.float32)
                    if bool(mask_cpu.any()):
                        v_reg_true_all.append(gt_intensity_cpu[mask_cpu])
                        v_reg_pred_all.append(pred_intensity_cpu[mask_cpu])

        val_loss = v_loss_sum / max(1, v_total)
        val_acc = v_correct / max(1, v_total)

        vyt = torch.cat(v_y_true_all, dim=0) if v_y_true_all else torch.empty((0,), dtype=torch.long)
        vyp = torch.cat(v_y_pred_all, dim=0) if v_y_pred_all else torch.empty((0,), dtype=torch.long)
        val_class_summary = classification_summary(vyt.tolist(), vyp.tolist(), EMOTIONS)
        val_f1 = float(val_class_summary.get("macro_f1", 0.0))

        val_mse = 0.0
        val_mae = 0.0
        val_ccc = 0.0
        val_intensity_n = 0
        if bool(args.use_intensity) and v_reg_true_all and v_reg_pred_all:
            rt = torch.cat(v_reg_true_all, dim=0).to(torch.float32)
            rp = torch.cat(v_reg_pred_all, dim=0).to(torch.float32)
            val_intensity_n = int(rt.numel())
            if val_intensity_n > 0:
                diff = (rp - rt).to(torch.float64)
                val_mse = float((diff * diff).mean().item())
                val_mae = float(diff.abs().mean().item())
                val_ccc = _ccc(rp, rt)

        if bool(args.use_intensity):
            print(
                "Epoch {e}: train_loss={tl:.4f} train_acc={ta:.4f} train_f1={tf:.4f} "
                "val_loss={vl:.4f} val_acc={va:.4f} val_f1={vf:.4f} "
                "val_mse={vmse:.4f} val_mae={vmae:.4f} val_ccc={vccc:.4f} (n={vn})".format(
                    e=epoch,
                    tl=train_loss,
                    ta=train_acc,
                    tf=train_f1,
                    vl=val_loss,
                    va=val_acc,
                    vf=val_f1,
                    vmse=val_mse,
                    vmae=val_mae,
                    vccc=val_ccc,
                    vn=val_intensity_n,
                )
            )
        else:
            print(
                "Epoch {e}: train_loss={tl:.4f} train_acc={ta:.4f} train_f1={tf:.4f} "
                "val_loss={vl:.4f} val_acc={va:.4f} val_f1={vf:.4f}".format(
                    e=epoch,
                    tl=train_loss,
                    ta=train_acc,
                    tf=train_f1,
                    vl=val_loss,
                    va=val_acc,
                    vf=val_f1,
                )
            )

        history["train_loss"].append(float(train_loss))
        history["train_acc"].append(float(train_acc))
        history["train_f1"].append(float(train_f1))
        history["val_loss"].append(float(val_loss))
        history["val_acc"].append(float(val_acc))
        history["val_f1"].append(float(val_f1))

        if bool(args.use_intensity):
            history["train_mse"].append(float(train_mse))
            history["train_mae"].append(float(train_mae))
            history["train_ccc"].append(float(train_ccc))
            history["train_intensity_n"].append(float(train_intensity_n))
            history["val_mse"].append(float(val_mse))
            history["val_mae"].append(float(val_mae))
            history["val_ccc"].append(float(val_ccc))
            history["val_intensity_n"].append(float(val_intensity_n))

        if val_acc > best_acc:
            # 目前以验证集 accuracy 作为最佳 checkpoint 的主排序指标，
            # 同时把宏平均 F1 和详细分类摘要一并写进 checkpoint 元数据。
            best_acc = val_acc
            best_epoch = epoch
            best_train_summary = train_class_summary
            best_val_summary = val_class_summary
            ckpt = {
                "model": model.state_dict(),
                "epoch": epoch,
                "best_acc": best_acc,
                "best_f1": float(val_f1),
                "args": vars(args),
                "cache_config": ds.config,
                "benchmark_tag": str(args.benchmark_tag),
                "split_manifest": str(args.split_manifest.expanduser()) if args.split_manifest is not None else None,
                "manifest_sha256": manifest_hash,
                "ablation": str(args.ablation),
                "zero_video": bool(args.zero_video),
                "zero_audio": bool(args.zero_audio),
                "zero_text": bool(args.zero_text),
                "best_val_summary": best_val_summary,
            }
            path = out_dir / "checkpoints" / "best.pt"
            torch.save(ckpt, path)
            print(f"Saved best checkpoint -> {path}")

    metrics_payload: dict[str, Any] = dict(history)
    metrics_payload["meta"] = {
        "benchmark_tag": str(args.benchmark_tag),
        "cached_dataset": str(cached_dir),
        "num_shards": len(shard_paths),
        "split_mode": str(args.split_mode),
        "split_manifest": str(args.split_manifest.expanduser()) if args.split_manifest is not None else None,
        "manifest_sha256": manifest_hash,
        "train_size": len(train_indices),
        "val_size": len(val_indices),
        "ablation": str(args.ablation),
        "zero_video": bool(args.zero_video),
        "zero_audio": bool(args.zero_audio),
        "zero_text": bool(args.zero_text),
        "args": _to_jsonable(vars(args)),
        "cache_config": _to_jsonable(ds.config),
    }
    if split_manifest is not None:
        metrics_payload["meta"]["manifest_summary"] = split_manifest.get("summary", {})
    if speaker_baseline is not None:
        metrics_payload["speaker_majority_baseline"] = speaker_baseline
    metrics_payload["best"] = {
        "epoch": int(best_epoch),
        "best_acc": float(best_acc),
        "best_train_summary": best_train_summary,
        "best_val_summary": best_val_summary,
    }

    _save_metrics_and_plots(out_dir, metrics_payload)


if __name__ == "__main__":
    main()
