from __future__ import annotations

import argparse
import json
import sys
import contextlib
import os
import math
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader, Subset
from tqdm import tqdm


# HuggingFace tokenizers may warn when DataLoader workers fork after tokenizers were used.
# Disabling tokenizers parallelism avoids deadlock risk and removes noisy warnings.
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")


def _ensure_project_root_on_path() -> None:
    """在脚本直跑时确保仓库根目录可导入。"""

    # When running as: python3 train_motion_audio.py
    # sys.path[0] is already the repo root, but keeping it explicit makes
    # direct execution and legacy-compat imports behave the same way.
    project_root = Path(__file__).resolve().parent
    project_root_str = str(project_root)
    if project_root_str not in sys.path:
        sys.path.insert(0, project_root_str)


_ensure_project_root_on_path()

from audio_aug import AudioAugConfig, augment_wav
from audio_aug import normalize_wav
from data import CachedMotionAudioDataset, collate
from manifest_utils import (
    EMOTIONS,
    TASK_MODES,
    build_validity_summary,
    filter_manifest_items_for_task,
    load_split_manifest,
    manifest_sha256,
    map_label_to_task_index,
    resolve_task_label_names,
    resolve_task_mode,
    select_manifest_items,
)
from metrics_utils import classification_summary, speaker_majority_baseline, speaker_only_baseline
from models import FusionClassifier
from prosody import ProsodyConfig, extract_prosody_features
from runtime_adapt import (
    detect_runtime,
    resolve_amp_mode,
    resolve_batch_size,
    resolve_prefetch_factor,
    resolve_worker_count,
    select_device,
)
from text_policy_utils import resolve_text_policy, select_text_for_policy


def parse_args():
    """定义训练入口的全部命令行参数。"""

    p = argparse.ArgumentParser(description="Train motion(flow)/rgb + audio + prosody fusion on cached dataset")
    p.add_argument("--cached-dataset", type=Path, default=None)
    p.add_argument("--feature-cache", type=Path, default=None, help="Optional feature-cache shard dir/file built by build_feature_cache.py")
    p.add_argument(
        "--task-mode",
        type=str,
        default="confounded_7way",
        choices=list(TASK_MODES),
        help="Evaluation/training task. confounded_7way keeps the legacy 7-way benchmark; within_speaker trains a speaker-specific subtask.",
    )
    p.add_argument(
        "--speaker-id",
        type=str,
        default="",
        help="Required when --task-mode=within_speaker. Must be one of A/B/C.",
    )
    p.add_argument("--epochs", type=int, default=50)
    p.add_argument("--batch-size", type=str, default="auto")
    p.add_argument("--num-workers", type=str, default="auto")
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument(
        "--monitor",
        type=str,
        default="val_f1",
        choices=["val_acc", "val_f1"],
        help="Metric used to select best checkpoint and early stopping.",
    )
    p.add_argument(
        "--early-stop-patience",
        type=int,
        default=4,
        help="Stop after N epochs without improvement on --monitor. Use 0 to disable early stopping.",
    )
    p.add_argument("--output-dir", type=Path, default=Path("outputs/motion_prosody"))
    p.add_argument("--split-manifest", type=Path, default=None, help="Optional split manifest generated by build_split_manifest.py")
    p.add_argument("--benchmark-tag", type=str, default="default", help="Free-form benchmark name recorded in metrics/checkpoint metadata")
    p.add_argument("--device", type=str, default="auto", choices=["auto", "cuda", "cpu"])
    p.add_argument("--freeze-audio", action="store_true")
    p.add_argument("--freeze-video", action="store_true", help="Freeze the video encoder")
    p.add_argument("--freeze-flow", action="store_true", help="Freeze only the optical-flow branch")
    p.add_argument("--freeze-rgb", action="store_true", help="Freeze only the RGB VideoMAE branch")
    p.add_argument("--freeze-prosody", action="store_true", help="Freeze the prosody MLP")

    # Video backbone
    p.add_argument(
        "--video-backbone",
        type=str,
        default="dual",
        choices=["flow", "videomae", "dual"],
        help="Video branch: optical-flow Conv3D, VideoMAE RGB backbone, or dual (flow+rgb)",
    )
    p.add_argument(
        "--video-model",
        type=str,
        default="MCG-NJU/videomae-large",
        help="HF model name for VideoMAE backbone (used when --video-backbone=videomae)",
    )

    # Audio backbone
    p.add_argument(
        "--audio-model",
        type=str,
        default="microsoft/wavlm-large",
        help="HF model name for audio encoder (use 'wav2vec2_base' for torchaudio wav2vec2)",
    )
    p.add_argument(
        "--audio-model-revision",
        type=str,
        default="",
        help="Optional HuggingFace revision / commit hash for the audio model. Use this when the default branch lacks model.safetensors.",
    )

    # Fusion settings
    p.add_argument(
        "--fusion-mode",
        type=str,
        default="gated_text",
        choices=["gated_text", "concat"],
        help="Fusion strategy: gated_text (default) or concat",
    )
    p.add_argument(
        "--gate-temperature",
        type=float,
        default=1.0,
        help="Gate temperature (>0). Lower => sharper gating, higher => smoother",
    )
    p.add_argument(
        "--gate-scale",
        type=float,
        default=1.0,
        help="Scale factor applied to the gate (controls contribution strength)",
    )
    p.add_argument(
        "--delta-scale",
        type=float,
        default=1.0,
        help="Scale factor applied to the delta (controls update magnitude)",
    )
    p.add_argument(
        "--modality-dropout",
        type=float,
        default=0.1,
        help="Randomly drop non-text modalities during training for robustness",
    )

    # Text branch (Mongolian)
    p.add_argument(
        "--text-model",
        type=str,
        default="xlm-roberta-large",
        help="HF model name for text encoder",
    )
    p.add_argument(
        "--text-policy",
        type=str,
        default="full",
        choices=["full", "mask_emotion_cues", "drop"],
        help="How text should be exposed to the model: full text, masked cues, or dropped entirely.",
    )
    p.add_argument("--freeze-text", action="store_true", help="Freeze the text (mBERT) encoder")
    p.add_argument(
        "--max-text-len",
        type=int,
        default=128,
        help="Tokenizer max_length for Mongolian text (truncation enabled)",
    )
    p.add_argument("--audio-aug", action="store_true")
    p.set_defaults(recompute_prosody_on_aug=True)
    p.add_argument(
        "--no-recompute-prosody-on-aug",
        dest="recompute_prosody_on_aug",
        action="store_false",
        help="When using --audio-aug, keep cached prosody vectors instead of recomputing from augmented wav",
    )
    p.add_argument(
        "--prosody-no-pitch",
        action="store_true",
        help="Disable pitch extraction (energy-only prosody; faster, less informative)",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--train-split", type=float, default=0.8)
    p.add_argument(
        "--split-mode",
        type=str,
        default="random",
        choices=["random", "sequential"],
        help="How to split train/val. 'random' is deterministic given --seed; 'sequential' keeps original order.",
    )
    p.add_argument("--zero-video", action="store_true", help="Zero video inputs for training/eval ablations")
    p.add_argument("--zero-audio", action="store_true", help="Zero audio-derived inputs (wav/audio_emb + prosody) for ablations")
    p.add_argument("--zero-text", action="store_true", help="Drop the text branch for training/eval ablations")
    p.add_argument(
        "--ablation",
        type=str,
        default="full",
        choices=["full", "text-only", "audio-only", "video-only", "no-text", "no-audio", "no-video"],
        help="Convenience preset for common modality ablations",
    )

    # Performance knobs (especially useful on CUDA).
    p.add_argument(
        "--pin-memory",
        action="store_true",
        help="Use DataLoader pin_memory for faster H2D copies (recommended on CUDA)",
    )
    p.add_argument(
        "--persistent-workers",
        action="store_true",
        help="Keep DataLoader workers alive across epochs (recommended when num-workers>0)",
    )
    p.add_argument(
        "--prefetch-factor",
        type=str,
        default="auto",
        help="DataLoader prefetch_factor (only used when num-workers>0)",
    )
    p.add_argument(
        "--amp",
        action="store_true",
        help="Enable CUDA AMP mixed precision for faster training",
    )
    p.add_argument(
        "--amp-mode",
        type=str,
        default="auto",
        choices=["auto", "off", "fp16", "bf16"],
        help="Automatic mixed precision mode. auto prefers bf16 then fp16 on CUDA.",
    )

    # Optional intensity regression (continuous label).
    p.add_argument(
        "--use-intensity",
        action="store_true",
        help=(
            "Enable auxiliary emotion intensity regression head and metrics. "
            "Requires cached samples to contain a finite 'intensity' value (else it is masked)."
        ),
    )
    p.add_argument(
        "--intensity-loss",
        type=str,
        default="mse",
        choices=["mse", "mae"],
        help="Regression loss type when --use-intensity is enabled",
    )
    p.add_argument(
        "--intensity-weight",
        type=float,
        default=1.0,
        help="Weight for regression loss in total loss: loss = CE + w * reg",
    )
    return p.parse_args()


def _autocast_context(device: torch.device, amp_mode: str) -> contextlib.AbstractContextManager[Any]:
    """根据解析后的 AMP 模式构造 autocast 上下文。"""

    if device.type != "cuda" or amp_mode == "off":
        return contextlib.nullcontext()
    amp_mod = getattr(torch, "amp", None)
    amp_dtype = torch.bfloat16 if amp_mode == "bf16" else torch.float16
    if amp_mod is not None and hasattr(amp_mod, "autocast"):
        return amp_mod.autocast("cuda", enabled=True, dtype=amp_dtype)  # type: ignore[attr-defined]
    return torch.cuda.amp.autocast(enabled=True)


def _cache_text_tokens(ds: CachedMotionAudioDataset, tokenizer: Any, max_text_len: int, *, text_policy: str) -> None:
    """预先把整集文本分词，避免每个 epoch / batch 重复 tokenizer。"""

    if not ds.samples:
        return
    if all("text_emb" in s for s in ds.samples):
        return
    if all("_text_input_ids" in s and "_text_attention_mask" in s for s in ds.samples):
        return
    texts = [
        select_text_for_policy(
            full_text=str(s.get("mn", "")),
            masked_text=str(s.get("masked_mn", "")),
            label_en=str(s.get("_global_label_en", "")) or None,
            policy=text_policy,
        )
        for s in ds.samples
    ]
    enc = tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=int(max_text_len),
        return_tensors="pt",
    )
    input_ids = enc["input_ids"].to(torch.long)
    attention_mask = enc["attention_mask"].to(torch.long)
    token_type_ids = enc.get("token_type_ids", None)
    for idx, sample in enumerate(ds.samples):
        sample["_text_input_ids"] = input_ids[idx].clone()
        sample["_text_attention_mask"] = attention_mask[idx].clone()
        if token_type_ids is not None:
            sample["_text_token_type_ids"] = token_type_ids[idx].to(torch.long).clone()


def _infer_text_dim(model_name: str) -> int:
    """根据常见文本模型名估计 hidden size，供跳过文本编码器初始化时使用。"""

    name = str(model_name).lower()
    if "large" in name:
        return 1024
    return 768


def _infer_audio_dim(model_name: str) -> int:
    """根据音频编码器类型估计 mean+std 池化后的输出维度。"""

    name = str(model_name).lower()
    if name == "wav2vec2_base":
        return 2 * 768
    if "large" in name:
        return 2 * 1024
    return 2 * 768


def _validate_cache_compatibility(ds: CachedMotionAudioDataset, args: argparse.Namespace) -> None:
    """提前检查 cache 是否满足当前训练配置。"""

    sample = ds[0]
    video_backbone = str(args.video_backbone)
    text_policy = resolve_text_policy(getattr(args, "text_policy", "full"))
    feature_cfg = ds.config.get("feature_cache", {}) if isinstance(ds.config, dict) else {}
    cached_text_policy = str(feature_cfg.get("text_policy", "") or "").strip().lower()

    if video_backbone == "dual":
        if bool(args.freeze_flow):
            if "flow_emb" not in sample and "flow" not in sample:
                raise RuntimeError("Training requires flow_emb or flow in cache, but neither is present.")
        elif "flow" not in sample:
            raise RuntimeError("Current config trains flow branch, but cache has no raw 'flow'. Build raw cache or freeze flow.")
        if bool(args.freeze_rgb):
            if "rgb_emb" not in sample and "rgb" not in sample:
                raise RuntimeError("Training requires rgb_emb or rgb in cache, but neither is present.")
        elif "rgb" not in sample:
            raise RuntimeError("Current config trains RGB branch, but cache has no raw 'rgb'. Build raw cache or freeze rgb.")
    elif video_backbone == "videomae":
        if bool(args.freeze_rgb):
            if "rgb_emb" not in sample and "rgb" not in sample:
                raise RuntimeError("Training requires rgb_emb or rgb in cache, but neither is present.")
        elif "rgb" not in sample:
            raise RuntimeError("Current config trains RGB branch, but cache has no raw 'rgb'.")
    else:
        if bool(args.freeze_flow):
            if "flow_emb" not in sample and "flow" not in sample:
                raise RuntimeError("Training requires flow_emb or flow in cache, but neither is present.")
        elif "flow" not in sample:
            raise RuntimeError("Current config trains flow branch, but cache has no raw 'flow'.")

    if bool(args.freeze_audio):
        if "audio_emb" not in sample and "audio" not in sample:
            raise RuntimeError("Training requires audio_emb or audio in cache, but neither is present.")
    elif "audio" not in sample:
        raise RuntimeError("Current config trains audio branch, but cache has no raw 'audio'. Freeze audio or rebuild cache.")

    if bool(args.freeze_text) and text_policy != "drop" and cached_text_policy and cached_text_policy != text_policy:
        raise RuntimeError(
            f"Feature-cache text_policy mismatch: cache={cached_text_policy} current={text_policy}. "
            "Rebuild feature cache or switch --text-policy."
        )

    if not bool(args.zero_text):
        if not bool(args.freeze_text) and "mn" not in sample:
            raise RuntimeError("Current config trains text branch, but cache has no raw Mongolian text.")
        if bool(args.freeze_text) and ("text_emb" not in sample and "mn" not in sample):
            raise RuntimeError("Training requires text_emb or mn in cache, but neither is present.")


def set_seed(seed: int):
    """固定 Python / NumPy / PyTorch 随机种子。"""

    import random
    import numpy as np

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _resolve_ablation_flags(args: argparse.Namespace) -> tuple[bool, bool, bool]:
    """把 `--ablation` 预设和显式 zero-* 标志合并成最终消融开关。"""

    ablation = str(getattr(args, "ablation", "full") or "full").strip().lower()
    zero_video = bool(getattr(args, "zero_video", False))
    zero_audio = bool(getattr(args, "zero_audio", False))
    zero_text = bool(getattr(args, "zero_text", False))
    presets = {
        "full": (False, False, False),
        "text-only": (True, True, False),
        "audio-only": (True, False, True),
        "video-only": (False, True, True),
        "no-text": (False, False, True),
        "no-audio": (False, True, False),
        "no-video": (True, False, False),
    }
    preset = presets.get(ablation)
    if preset is not None:
        zero_video = zero_video or preset[0]
        zero_audio = zero_audio or preset[1]
        zero_text = zero_text or preset[2]
    return zero_video, zero_audio, zero_text


def _macro_f1(y_true: torch.Tensor, y_pred: torch.Tensor, num_classes: int) -> float:
    """从标签张量直接计算 macro-F1。"""

    # y_true/y_pred: (N,) int64
    if y_true.numel() == 0:
        return 0.0
    y_true = y_true.to(torch.long)
    y_pred = y_pred.to(torch.long)

    f1_sum = 0.0
    for c in range(int(num_classes)):
        tp = int(((y_true == c) & (y_pred == c)).sum().item())
        fp = int(((y_true != c) & (y_pred == c)).sum().item())
        fn = int(((y_true == c) & (y_pred != c)).sum().item())
        denom = (2 * tp + fp + fn)
        f1_c = (2 * tp / denom) if denom > 0 else 0.0
        f1_sum += float(f1_c)
    return float(f1_sum / max(1, int(num_classes)))


def _ccc(x: torch.Tensor, y: torch.Tensor) -> float:
    """计算 Concordance Correlation Coefficient。

    公式为：
    `CCC = 2 * cov(x, y) / (var(x) + var(y) + (mean_x - mean_y)^2)`。

    它同时惩罚：
    - 相关性差；
    - 均值偏移；
    - 方差不一致。

    因此比单纯的 Pearson 更适合连续强度回归评估。
    """
    x = x.flatten().to(torch.float64)
    y = y.flatten().to(torch.float64)
    n = int(x.numel())
    if n < 2:
        return 0.0
    mx = float(x.mean().item())
    my = float(y.mean().item())
    vx = float(x.var(unbiased=False).item())
    vy = float(y.var(unbiased=False).item())
    cov = float(((x - mx) * (y - my)).mean().item())
    denom = vx + vy + (mx - my) ** 2
    if denom <= 0:
        return 0.0
    return float((2.0 * cov) / denom)


def _to_jsonable(value: Any) -> Any:
    """把 Path/tuple 等对象递归转换成可写入 JSON 的结构。"""

    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(k): _to_jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_to_jsonable(v) for v in value]
    return value


def _save_metrics_and_plots(out_dir: Path, metrics: dict[str, Any]) -> None:
    """落盘训练指标，并尽量生成训练过程图表。"""

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")

    # Plot (optional). If matplotlib isn't installed, we still keep metrics.json.
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:
        print(f"Plot skipped (matplotlib not available): {type(e).__name__}: {e}")
        print("Install with: pip install matplotlib")
        return

    epochs = list(range(1, len(metrics.get("train_loss", [])) + 1))
    if not epochs:
        return

    label_names = list(
        metrics.get("meta", {}).get(
            "label_names",
            metrics.get("meta", {}).get("cache_config", {}).get("emotions", EMOTIONS),
        )
    )

    # Accuracy plot
    plt.figure(figsize=(8, 4.5))
    if "train_acc" in metrics:
        plt.plot(epochs, metrics["train_acc"], label="train")
    if "val_acc" in metrics:
        plt.plot(epochs, metrics["val_acc"], label="val")
    plt.xlabel("epoch")
    plt.ylabel("accuracy")
    plt.title("Accuracy vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "accuracy_curve.png", dpi=160)
    plt.close()

    # Loss plot
    plt.figure(figsize=(8, 4.5))
    if "train_loss" in metrics:
        plt.plot(epochs, metrics["train_loss"], label="train")
    if "val_loss" in metrics:
        plt.plot(epochs, metrics["val_loss"], label="val")
    plt.xlabel("epoch")
    plt.ylabel("loss")
    plt.title("Loss vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "loss_curve.png", dpi=160)
    plt.close()

    # Macro-F1 plot
    plt.figure(figsize=(8, 4.5))
    if "train_f1" in metrics:
        plt.plot(epochs, metrics["train_f1"], label="train")
    if "val_f1" in metrics:
        plt.plot(epochs, metrics["val_f1"], label="val")
    plt.xlabel("epoch")
    plt.ylabel("macro_f1")
    plt.title("Macro-F1 vs Epoch")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "macro_f1_curve.png", dpi=160)
    plt.close()

    # Per-class recall curves
    train_recall_history = metrics.get("train_per_class_recall", [])
    val_recall_history = metrics.get("val_per_class_recall", [])
    if isinstance(train_recall_history, list) and isinstance(val_recall_history, list) and (train_recall_history or val_recall_history):
        fig, axes = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
        plot_specs = [
            (axes[0], train_recall_history, "Train Per-Class Recall"),
            (axes[1], val_recall_history, "Val Per-Class Recall"),
        ]
        for ax, recall_history, title in plot_specs:
            if not recall_history:
                ax.set_title(f"{title} (empty)")
                ax.grid(True, alpha=0.3)
                continue
            for label_name in label_names:
                values = [float(step.get(label_name, 0.0)) for step in recall_history]
                ax.plot(epochs[: len(values)], values, label=label_name)
            ax.set_ylabel("recall")
            ax.set_title(title)
            ax.set_ylim(0.0, 1.05)
            ax.grid(True, alpha=0.3)
        axes[-1].set_xlabel("epoch")
        handles, labels = axes[0].get_legend_handles_labels()
        if handles:
            fig.legend(handles, labels, loc="upper center", ncol=min(4, max(1, len(labels))), frameon=False)
        fig.tight_layout(rect=(0, 0, 1, 0.95))
        fig.savefig(out_dir / "per_class_recall_curve.png", dpi=160)
        plt.close(fig)

    # Best-val confusion matrix heatmap
    best_val_summary = metrics.get("best", {}).get("best_val_summary", {})
    matrix = best_val_summary.get("confusion_matrix", [])
    if isinstance(matrix, list) and matrix:
        plt.figure(figsize=(8.5, 7))
        ax = plt.gca()
        im = ax.imshow(matrix, cmap="Blues")
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        ax.set_title("Best Val Confusion Matrix")
        ax.set_xlabel("pred")
        ax.set_ylabel("true")
        ax.set_xticks(range(len(label_names)))
        ax.set_yticks(range(len(label_names)))
        ax.set_xticklabels(label_names, rotation=45, ha="right")
        ax.set_yticklabels(label_names)
        vmax = max((max(row) for row in matrix if row), default=0)
        threshold = vmax / 2.0 if vmax > 0 else 0.0
        for i, row in enumerate(matrix):
            for j, value in enumerate(row):
                ax.text(
                    j,
                    i,
                    str(int(value)),
                    ha="center",
                    va="center",
                    color="white" if float(value) > threshold else "black",
                    fontsize=8,
                )
        plt.tight_layout()
        plt.savefig(out_dir / "confusion_matrix_best_val.png", dpi=160)
        plt.close()


def _print_split_label_hist(name: str, ds: CachedMotionAudioDataset, indices: list[int], label_names: list[str]) -> None:
    """打印某个子集的标签直方图，便于快速检查切分是否异常。"""

    num_classes = len(label_names)
    counts = torch.zeros(num_classes, dtype=torch.long)
    oob: list[tuple[int, int]] = []
    for i in indices:
        y = ds.samples[i].get("label", None)
        if isinstance(y, torch.Tensor):
            y_int = int(y.item())
        else:
            if y is None:
                oob.append((i, -1))
                continue
            y_int = int(y)
        if 0 <= y_int < num_classes:
            counts[y_int] += 1
        else:
            oob.append((i, y_int))
    total = int(counts.sum().item())
    parts = [f"{label_names[k]}:{int(v)}" for k, v in enumerate(counts.tolist())]
    print(f"{name} label histogram (n={total}): " + " ".join(parts))
    if oob:
        shown = ", ".join([f"idx={i}/label={y}" for i, y in oob[:10]])
        print(f"WARNING: {name} has out-of-range labels (show up to 10): {shown}")


def _prepare_dataset_for_task(ds: CachedMotionAudioDataset, task_mode: str, speaker_id: str | None) -> list[str]:
    """把缓存样本标签映射成当前任务模式下的局部标签空间。"""

    label_names = resolve_task_label_names(task_mode, speaker_id)
    for idx, sample in enumerate(ds.samples):
        raw_label = sample.get("label", None)
        raw_label_idx: int | None = None
        if isinstance(raw_label, torch.Tensor):
            raw_label_idx = int(raw_label.item())
        elif raw_label is not None:
            raw_label_idx = int(raw_label)
        global_label_en = EMOTIONS[raw_label_idx] if raw_label_idx is not None and 0 <= raw_label_idx < len(EMOTIONS) else None
        sample["_global_label_en"] = global_label_en
        task_label_idx = map_label_to_task_index(global_label_en, task_mode, speaker_id)
        if task_label_idx is None:
            continue
        if isinstance(raw_label, torch.Tensor):
            sample["label"] = torch.tensor(task_label_idx, dtype=torch.long)
        else:
            sample["label"] = int(task_label_idx)
    return label_names


def _infer_cached_embedding_dims(samples: list[dict[str, Any]]) -> dict[str, int]:
    """从缓存样本里探测 embedding 维度，用于跳过已冻结编码器的初始化。"""

    dims: dict[str, int] = {}
    for key in ("audio_emb", "text_emb", "rgb_emb", "flow_emb"):
        for sample in samples:
            value = sample.get(key, None)
            if isinstance(value, torch.Tensor) and value.ndim >= 1:
                dims[key] = int(value.shape[-1])
                break
    return dims


def _write_best_val_inference_outputs(
    out_dir: Path,
    *,
    records: list[dict[str, Any]],
    metrics_summary: dict[str, Any],
) -> None:
    """把最佳 epoch 的验证集逐样本结果和汇总指标写到 run 目录。"""

    out_dir.mkdir(parents=True, exist_ok=True)
    jsonl_path = out_dir / "inference_val.jsonl"
    with jsonl_path.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    metrics_path = out_dir / "inference_val.metrics.json"
    metrics_path.write_text(json.dumps(metrics_summary, ensure_ascii=False, indent=2), encoding="utf-8")


def _write_results_summary(out_dir: Path, metrics: dict[str, Any]) -> None:
    """生成一个便于人工快速浏览的实验摘要 Markdown。"""

    out_dir.mkdir(parents=True, exist_ok=True)
    best = metrics.get("best", {})
    validity = metrics.get("validity", {})
    speaker_majority = metrics.get("speaker_majority_baseline", {})
    speaker_only = metrics.get("speaker_only_baseline", {})
    meta = metrics.get("meta", {})
    best_val = best.get("best_val_summary", {})
    lines = [
        "# Run Summary",
        "",
        f"- task_mode: `{validity.get('task_mode', 'confounded_7way')}`",
        f"- speaker_id: `{validity.get('speaker_id')}`",
        f"- text_policy: `{meta.get('text_policy', 'full')}`",
        f"- scientific_validity: `{validity.get('scientific_validity')}`",
        f"- claim_scope: `{validity.get('claim_scope')}`",
        f"- recommended_interpretation: {validity.get('recommended_interpretation', '')}",
        "",
        "## Best Validation",
        "",
        f"- epoch: `{best.get('epoch')}`",
        f"- accuracy: `{best_val.get('accuracy')}`",
        f"- macro_f1: `{best_val.get('macro_f1')}`",
        "",
        "## Baselines",
        "",
        f"- speaker_majority_accuracy: `{speaker_majority.get('accuracy')}`",
        f"- speaker_majority_macro_f1: `{speaker_majority.get('macro_f1')}`",
        f"- speaker_only_accuracy: `{speaker_only.get('accuracy')}`",
        f"- speaker_only_macro_f1: `{speaker_only.get('macro_f1')}`",
        "",
        "## Artifacts",
        "",
        "- `metrics.json`",
        "- `checkpoints/best.pt`",
        "- `checkpoints/last.pt`",
        "- `inference_val.jsonl`",
        "- `inference_val.metrics.json`",
        "- training curves and confusion matrix PNGs",
    ]
    (out_dir / "results_summary.md").write_text("\n".join(lines).strip() + "\n", encoding="utf-8")


def main():
    """训练主流程。

    这部分串起了主工程的完整训练链路：
    1. 读取缓存 shard；
    2. 根据 manifest 或随机策略切分 train/val；
    3. 构造 tokenizer、模型、优化器与 AMP；
    4. 逐 epoch 进行训练与验证；
    5. 保存最佳 checkpoint 和完整指标。
    """

    args = parse_args()
    if args.cached_dataset is None and args.feature_cache is None:
        raise RuntimeError("Provide at least one of --cached-dataset or --feature-cache")
    set_seed(args.seed)
    args.text_policy = resolve_text_policy(args.text_policy)
    zero_video, zero_audio, zero_text = _resolve_ablation_flags(args)
    if str(args.text_policy) == "drop":
        zero_text = True
    args.zero_video = zero_video
    args.zero_audio = zero_audio
    args.zero_text = zero_text

    profile = detect_runtime(args.device)
    device = select_device(args.device)
    if device.type == "cuda":
        try:
            name = torch.cuda.get_device_name(0)
            print(f"Using device: cuda (0) - {name}")
        except Exception:
            print("Using device: cuda")
    else:
        print(f"Using device: {device}")
    print(f"Runtime profile: {json.dumps(profile.to_jsonable(), ensure_ascii=False)}")

    # GPU perf hints
    if device.type == "cuda":
        try:
            torch.backends.cudnn.benchmark = True
        except Exception:
            pass
        try:
            torch.set_float32_matmul_precision("high")
        except Exception:
            pass

    # Print cached shard paths (helps debug loading and ensures reproducibility).
    cache_source = args.feature_cache.expanduser() if args.feature_cache is not None else args.cached_dataset.expanduser()
    if args.split_manifest is not None and not args.split_manifest.expanduser().exists():
        raise FileNotFoundError(f"Split manifest not found: {args.split_manifest.expanduser()}")
    if cache_source.is_file():
        shard_paths = [cache_source]
    else:
        shard_paths = sorted(
            cache_source.glob("*.pt"),
            key=lambda p: int(p.stem) if p.stem.isdigit() else p.stem,
        )
    print(f"Training cache path: {cache_source}")
    print(f"Found {len(shard_paths)} shard(s):")
    for p in shard_paths:
        print(f"  - {p}")

    ds = CachedMotionAudioDataset(cache_source)
    dataset_kind = ""
    if isinstance(ds.config, dict):
        dataset_kind = str(
            ds.config.get("source_manifest", {}).get("dataset_kind")
            or ds.config.get("dataset_kind", "")
            or ""
        ).strip()
    if not dataset_kind and ds.samples:
        dataset_kind = str(ds.samples[0].get("dataset_kind", "") or "").strip()
    task_mode = resolve_task_mode(args.task_mode)
    task_speaker_id = str(args.speaker_id).strip().upper() or None
    task_label_names = _prepare_dataset_for_task(ds, task_mode, task_speaker_id)
    cached_embedding_dims = _infer_cached_embedding_dims(ds.samples)
    _validate_cache_compatibility(ds, args)
    split_manifest = None
    manifest_hash = None
    manifest_summary: dict[str, Any] = {}
    validity_summary = build_validity_summary(manifest_summary, task_mode, task_speaker_id)
    train_manifest_items: list[dict[str, Any]] = []
    val_manifest_items: list[dict[str, Any]] = []

    if args.split_manifest is not None:
        split_manifest = load_split_manifest(args.split_manifest.expanduser())
        manifest_hash = manifest_sha256(args.split_manifest.expanduser())
        manifest_summary = split_manifest.get("summary", {})
        dataset_kind = str(split_manifest.get("dataset_kind", dataset_kind) or dataset_kind)
        validity_summary = build_validity_summary(manifest_summary, task_mode, task_speaker_id)
        train_manifest_items = filter_manifest_items_for_task(
            select_manifest_items(split_manifest, "train"),
            task_mode,
            task_speaker_id,
        )
        val_manifest_items = filter_manifest_items_for_task(
            select_manifest_items(split_manifest, "val"),
            task_mode,
            task_speaker_id,
        )

        stem_to_index: dict[str, int] = {}
        duplicate_stems: set[str] = set()
        for idx, sample in enumerate(ds.samples):
            stem = str(sample.get("stem", idx))
            if stem in stem_to_index:
                duplicate_stems.add(stem)
                continue
            stem_to_index[stem] = idx
        if duplicate_stems:
            shown = ", ".join(sorted(list(duplicate_stems))[:10])
            print(f"WARNING: duplicate stems in cached dataset; first occurrence will be used. Example(s): {shown}")

        def _indices_for_manifest(items: list[dict[str, Any]], name: str) -> tuple[list[int], list[dict[str, Any]]]:
            """把 manifest 中的样本序号映射成缓存数据集索引。

            manifest 是基于 XLSX 生成的，可能包含“有标签但缺少原始媒体”的样本。
            这些样本不会出现在 raw/feature cache 里，因此这里选择告警并跳过，
            而不是让整轮训练因为 1 条缺失样本直接失败。
            """

            indices: list[int] = []
            kept_items: list[dict[str, Any]] = []
            missing_stems: list[str] = []
            for item in items:
                stem = str(item.get("seq", ""))
                if stem in stem_to_index:
                    indices.append(stem_to_index[stem])
                    kept_items.append(item)
                else:
                    missing_stems.append(stem)
            if missing_stems:
                preview = ", ".join(missing_stems[:10])
                print(
                    f"WARNING: {name} split manifest contains {len(missing_stems)} stem(s) missing from cache; "
                    f"they will be skipped. Example(s): {preview}",
                    flush=True,
                )
            return indices, kept_items

        train_indices, train_manifest_items = _indices_for_manifest(train_manifest_items, "train")
        val_indices, val_manifest_items = _indices_for_manifest(val_manifest_items, "val")
        if not train_indices or not val_indices:
            raise RuntimeError("Split manifest produced an empty train or val subset.")
        print(f"Using split manifest: {args.split_manifest.expanduser()}")
        print(f"Manifest sha256: {manifest_hash}")
    else:
        # deterministic split
        candidate_indices = list(range(len(ds)))
        if task_mode == "within_speaker":
            candidate_indices = [
                idx
                for idx, sample in enumerate(ds.samples)
                if str(sample.get("speaker_id", "UNKNOWN")).strip().upper() == str(task_speaker_id or "")
                and str(sample.get("_global_label_en", "")) in set(task_label_names)
            ]
            if not candidate_indices:
                raise RuntimeError(f"No cached samples found for within_speaker task and speaker {task_speaker_id}.")
        n = len(candidate_indices)
        n_train = int(n * args.train_split)
        if args.split_mode == "random":
            g = torch.Generator()
            g.manual_seed(int(args.seed))
            perm = torch.randperm(n, generator=g).tolist()
            indices = [candidate_indices[i] for i in perm]
        else:
            indices = list(candidate_indices)
        train_indices = indices[:n_train]
        val_indices = indices[n_train:]
    train_ds = Subset(ds, train_indices)
    val_ds = Subset(ds, val_indices)
    _print_split_label_hist("train", ds, train_indices, task_label_names)
    _print_split_label_hist("val", ds, val_indices, task_label_names)
    speaker_baseline = None
    speaker_only = None
    if split_manifest is not None and train_manifest_items and val_manifest_items and task_mode == "confounded_7way":
        speaker_baseline = speaker_majority_baseline(train_manifest_items, val_manifest_items, task_label_names)
        speaker_only = speaker_only_baseline(train_manifest_items, val_manifest_items, task_label_names)

    using_feature_cache = bool(args.feature_cache is not None or ds.config.get("feature_cache"))
    resolved_batch_size = resolve_batch_size(
        args.batch_size,
        phase="train",
        profile=profile,
        feature_cache=using_feature_cache,
        video_backbone=str(args.video_backbone),
        freeze_audio=bool(args.freeze_audio),
        freeze_text=bool(args.freeze_text),
        freeze_flow=bool(args.freeze_video or args.freeze_flow),
        freeze_rgb=bool(args.freeze_video or args.freeze_rgb),
    )
    resolved_num_workers = resolve_worker_count(
        args.num_workers,
        phase="train",
        profile=profile,
        dataset_in_memory=True,
        total_items=len(ds),
    )
    pin_memory = device.type == "cuda"
    persistent_workers = bool(args.persistent_workers) if int(resolved_num_workers) > 0 else False
    prefetch_factor = resolve_prefetch_factor(args.prefetch_factor, num_workers=int(resolved_num_workers))
    dl_kwargs = {
        "num_workers": int(resolved_num_workers),
        "collate_fn": collate,
        "pin_memory": pin_memory,
    }
    if int(resolved_num_workers) > 0:
        dl_kwargs["persistent_workers"] = persistent_workers
        if prefetch_factor is not None:
            dl_kwargs["prefetch_factor"] = max(1, int(prefetch_factor))

    train_loader = DataLoader(train_ds, batch_size=int(resolved_batch_size), shuffle=True, **dl_kwargs)
    val_loader = DataLoader(val_ds, batch_size=int(resolved_batch_size), shuffle=False, **dl_kwargs)

    tokenizer = None
    needs_text_tokenizer = (not bool(args.zero_text)) and (not all("text_emb" in s for s in ds.samples))
    if needs_text_tokenizer:
        try:
            from transformers import AutoTokenizer
        except Exception as e:
            raise RuntimeError(
                "transformers is required for tri-modal training (text branch). Install with: pip install transformers"
            ) from e

        tokenizer = AutoTokenizer.from_pretrained(str(args.text_model))
        _cache_text_tokens(ds, tokenizer, int(args.max_text_len), text_policy=str(args.text_policy))

    skip_audio_encoder_init = bool(using_feature_cache and args.freeze_audio and ("audio_emb" in cached_embedding_dims))
    if bool(args.zero_audio) and "audio_emb" not in cached_embedding_dims:
        skip_audio_encoder_init = True
    skip_text_encoder_init = bool(using_feature_cache and args.freeze_text and ("text_emb" in cached_embedding_dims))
    if bool(args.zero_text) and "text_emb" not in cached_embedding_dims:
        skip_text_encoder_init = True

    model = FusionClassifier(
        num_classes=len(task_label_names),
        freeze_audio=args.freeze_audio,
        audio_dim=cached_embedding_dims.get("audio_emb", _infer_audio_dim(str(args.audio_model))),
        rgb_dim=cached_embedding_dims.get("rgb_emb"),
        freeze_video=bool(args.freeze_video),
        freeze_flow=bool(args.freeze_video or args.freeze_flow),
        freeze_rgb=bool(args.freeze_video or args.freeze_rgb),
        freeze_prosody=bool(args.freeze_prosody),
        text_model=str(args.text_model),
        text_dim=cached_embedding_dims.get("text_emb", _infer_text_dim(str(args.text_model))),
        freeze_text=bool(args.freeze_text),
        audio_model=str(args.audio_model),
        audio_model_revision=(str(args.audio_model_revision).strip() or None),
        video_backbone=str(args.video_backbone),
        video_model=str(args.video_model),
        fusion_mode=str(args.fusion_mode),
        modality_dropout=float(args.modality_dropout),
        gate_temperature=float(args.gate_temperature),
        gate_scale=float(args.gate_scale),
        delta_scale=float(args.delta_scale),
        skip_audio_encoder_init=skip_audio_encoder_init,
        skip_text_encoder_init=skip_text_encoder_init,
        skip_rgb_encoder_init=bool(
            using_feature_cache
            and (bool(args.freeze_video) or bool(args.freeze_rgb))
            and ("rgb_emb" in cached_embedding_dims)
            and str(args.video_backbone) in {"dual", "videomae"}
        ),
    ).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    loss_fn = torch.nn.CrossEntropyLoss()

    aug_cfg = AudioAugConfig(sample_rate=int(ds.config.get("sample_rate", 24000)))
    prosody_cfg = ProsodyConfig(sample_rate=aug_cfg.sample_rate, use_pitch=(not args.prosody_no_pitch))

    requested_amp_mode = str(args.amp_mode)
    if bool(args.amp) and requested_amp_mode == "auto":
        requested_amp_mode = "auto"
    resolved_amp_mode = resolve_amp_mode(requested_amp_mode, profile)
    amp_mod = getattr(torch, "amp", None)
    if amp_mod is not None and hasattr(amp_mod, "GradScaler"):
        try:
            scaler = amp_mod.GradScaler("cuda", enabled=(resolved_amp_mode == "fp16"))  # type: ignore[attr-defined]
        except Exception:
            scaler = torch.cuda.amp.GradScaler(enabled=(resolved_amp_mode == "fp16"))
    else:
        scaler = torch.cuda.amp.GradScaler(enabled=(resolved_amp_mode == "fp16"))

    print(
        json.dumps(
            {
                "resolved_batch_size": int(resolved_batch_size),
                "resolved_num_workers": int(resolved_num_workers),
                "resolved_prefetch_factor": int(prefetch_factor) if prefetch_factor is not None else None,
                "pin_memory": bool(pin_memory),
                "using_feature_cache": using_feature_cache,
                "amp_mode": resolved_amp_mode,
            },
            ensure_ascii=False,
            indent=2,
        ),
        flush=True,
    )

    best_acc = 0.0
    best_f1 = 0.0
    best_epoch = 0
    best_monitor_value = float("-inf")
    best_monitor_name = str(args.monitor)
    epochs_without_improvement = 0
    best_val_summary: dict[str, Any] = {}
    best_train_summary: dict[str, Any] = {}
    out_dir = args.output_dir.expanduser()
    (out_dir / "checkpoints").mkdir(parents=True, exist_ok=True)

    history: dict[str, Any] = {
        "train_loss": [],
        "train_acc": [],
        "train_f1": [],
        "val_loss": [],
        "val_acc": [],
        "val_f1": [],
        "train_per_class_recall": [],
        "val_per_class_recall": [],
    }

    if bool(args.use_intensity):
        history.update(
            {
                "train_mse": [],
                "train_mae": [],
                "train_ccc": [],
                "train_intensity_n": [],
                "val_mse": [],
                "val_mae": [],
                "val_ccc": [],
                "val_intensity_n": [],
            }
        )

    warned_audio_aug_ignored = False

    for epoch in range(1, args.epochs + 1):
        model.train()
        total = 0
        correct = 0
        running = 0.0
        y_true_all: list[torch.Tensor] = []
        y_pred_all: list[torch.Tensor] = []

        reg_pred_all: list[torch.Tensor] = []
        reg_true_all: list[torch.Tensor] = []
        for batch in tqdm(train_loader, desc=f"Epoch {epoch}/{args.epochs} [train]"):
            nb = pin_memory and device.type == "cuda"

            cached_audio_emb = batch.get("audio_emb", None)
            has_audio = "audio" in batch
            use_audio_emb = cached_audio_emb is not None and (bool(args.freeze_audio) or not has_audio)
            flow_emb_t = batch.get("flow_emb", None)
            rgb_emb_t = batch.get("rgb_emb", None)
            text_emb_t = batch.get("text_emb", None) if bool(args.freeze_text) else None

            # Keep audio augmentation on CPU to avoid costly per-sample CPU<->GPU transfers
            # (and to avoid torchaudio CUDA resample instability).
            prosody_cpu = batch["prosody"]
            y = batch["labels"].to(device, non_blocking=nb)

            if use_audio_emb:
                # 已缓存 audio_emb 时，训练阶段不再重新跑 WavLM。
                # 这时 `--audio-aug` 无法作用到 embedding，因此只能提示并忽略。
                if args.audio_aug and not warned_audio_aug_ignored:
                    print("WARNING: audio_emb detected; --audio-aug is ignored for cached embeddings.")
                    warned_audio_aug_ignored = True
                if has_audio:
                    wav_cpu = batch["audio"]
                else:
                    wav_cpu = torch.zeros((prosody_cpu.shape[0], 1), dtype=torch.float32)
                audio_lens = batch.get("audio_lens", None)
            else:
                if not has_audio:
                    raise RuntimeError("Batch is missing 'audio' and no 'audio_emb' provided. Re-run predecode with --audio-repr raw or wavlm.")
                wav_cpu = batch["audio"]
                # 先做基础 RMS 归一化，再做可选增强，最后再归一化一次，
                # 避免增强后的幅值漂移把编码器输入尺度拉乱。
                wav_cpu = normalize_wav(wav_cpu, target_rms=0.1)
                if args.audio_aug:
                    wav_cpu = augment_wav(wav_cpu, aug_cfg)
                    wav_cpu = normalize_wav(wav_cpu, target_rms=0.1)
                    if args.recompute_prosody_on_aug:
                        # 韵律来自增强后的波形时，prosody 才与模型实际看到的音频一致。
                        prosody_list = [extract_prosody_features(wav_cpu[i].detach(), prosody_cfg) for i in range(wav_cpu.shape[0])]
                        prosody_cpu = torch.stack(prosody_list, dim=0)
                audio_lens = batch["audio_lens"]

            if str(args.video_backbone) == "videomae":
                if not bool(args.freeze_rgb) and "rgb" not in batch:
                    raise RuntimeError("Batch is missing 'rgb'. Re-run predecode with --video-repr rgb or both.")
                flow = None
                rgb = batch["rgb"].to(device, non_blocking=nb) if "rgb" in batch else None
            elif str(args.video_backbone) == "dual":
                if not bool(args.freeze_flow) and "flow" not in batch:
                    raise RuntimeError("Batch must contain raw 'flow' when the flow branch is trainable.")
                if not bool(args.freeze_rgb) and "rgb" not in batch:
                    raise RuntimeError("Batch must contain raw 'rgb' when the RGB branch is trainable.")
                flow = batch["flow"].to(device, non_blocking=nb) if "flow" in batch else None
                rgb = batch["rgb"].to(device, non_blocking=nb) if "rgb" in batch else None
            else:
                if not bool(args.freeze_flow) and "flow" not in batch:
                    raise RuntimeError("Batch is missing 'flow'. Re-run predecode with --video-repr flow or both.")
                flow = batch["flow"].to(device, non_blocking=nb) if "flow" in batch else None
                rgb = None

            if flow_emb_t is not None and bool(args.freeze_flow):
                flow_emb_t = flow_emb_t.to(device, non_blocking=nb)
            else:
                flow_emb_t = None
            if rgb_emb_t is not None and bool(args.freeze_rgb):
                rgb_emb_t = rgb_emb_t.to(device, non_blocking=nb)
            else:
                rgb_emb_t = None

            wav = wav_cpu.to(device, non_blocking=nb)
            audio_lens_t = audio_lens.to(device, non_blocking=nb) if audio_lens is not None else None
            prosody = prosody_cpu.to(device, non_blocking=nb)
            audio_emb_t = cached_audio_emb.to(device, non_blocking=nb) if use_audio_emb and cached_audio_emb is not None else None
            if bool(args.zero_video):
                if flow is not None:
                    flow = torch.zeros_like(flow)
                if rgb is not None:
                    rgb = torch.zeros_like(rgb)
                if flow_emb_t is not None:
                    flow_emb_t = torch.zeros_like(flow_emb_t)
                if rgb_emb_t is not None:
                    rgb_emb_t = torch.zeros_like(rgb_emb_t)
            if bool(args.zero_audio):
                wav = torch.zeros_like(wav)
                prosody = torch.zeros_like(prosody)
                if audio_emb_t is not None:
                    audio_emb_t = torch.zeros_like(audio_emb_t)

            mn_list = batch.get("mn", None)
            if mn_list is None:
                raise RuntimeError("Batch is missing 'mn'. Please re-run predecode with mn saved.")
            if text_emb_t is not None:
                text_emb_t = text_emb_t.to(device, non_blocking=nb)
            text_inputs = batch.get("text_inputs", None)
            if not bool(args.zero_text):
                if text_inputs is not None:
                    text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}
                elif text_emb_t is None:
                    if tokenizer is None:
                        raise RuntimeError(
                            "Text tokenizer is unavailable and batch is missing text_emb/text_inputs. "
                            "Rebuild a feature cache with text embeddings or provide local text model files."
                        )
                    text_inputs = tokenizer(
                        [
                            select_text_for_policy(
                                full_text=str(mn_list[i]),
                                masked_text=str(batch.get("masked_mn", [""] * len(mn_list))[i]),
                                label_en=str(batch.get("_global_label_en", [""] * len(mn_list))[i]) or None,
                                policy=str(args.text_policy),
                            )
                            for i in range(len(mn_list))
                        ],
                        padding=True,
                        truncation=True,
                        max_length=int(args.max_text_len),
                        return_tensors="pt",
                    )
                    text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}
            else:
                text_inputs = None
                text_emb_t = None

            opt.zero_grad(set_to_none=True)
            amp_ctx = _autocast_context(device, resolved_amp_mode)

            with amp_ctx:
                if bool(args.use_intensity):
                    logits, pred_intensity = model(
                        flow,
                        wav,
                        prosody,
                        text_inputs=text_inputs,
                        return_intensity=True,
                        rgb=rgb,
                        audio_lens=audio_lens_t,
                        audio_emb=audio_emb_t,
                        flow_emb=flow_emb_t,
                        rgb_emb=rgb_emb_t,
                        text_emb=text_emb_t,
                    )
                else:
                    logits = model(
                        flow,
                        wav,
                        prosody,
                        text_inputs=text_inputs,
                        rgb=rgb,
                        audio_lens=audio_lens_t,
                        audio_emb=audio_emb_t,
                        flow_emb=flow_emb_t,
                        rgb_emb=rgb_emb_t,
                        text_emb=text_emb_t,
                    )

                # 主任务始终是情绪分类交叉熵。
                loss = loss_fn(logits, y)

                if bool(args.use_intensity):
                    gt_intensity = batch["intensity"].to(device, non_blocking=nb).to(torch.float32)
                    intensity_mask = batch["intensity_mask"].to(device, non_blocking=nb)
                    if intensity_mask.any():
                        pred_f = pred_intensity.to(torch.float32)[intensity_mask]
                        gt_f = gt_intensity[intensity_mask]
                        if str(args.intensity_loss).lower().strip() == "mae":
                            reg_loss = torch.abs(pred_f - gt_f).mean()
                        else:
                            reg_loss = torch.square(pred_f - gt_f).mean()
                        # 多任务总损失：
                        #   total_loss = CE + intensity_weight * reg_loss
                        # 其中 reg_loss 是 MSE 或 MAE。
                        loss = loss + float(args.intensity_weight) * reg_loss

            scaler.scale(loss).backward()
            scaler.step(opt)
            scaler.update()

            running += loss.item() * y.size(0)
            pred = logits.argmax(dim=1)
            correct += (pred == y).sum().item()
            total += y.size(0)

            y_true_all.append(y.detach().cpu())
            y_pred_all.append(pred.detach().cpu())

            if bool(args.use_intensity):
                gt_intensity_cpu = batch["intensity"].detach().cpu().to(torch.float32)
                mask_cpu = batch["intensity_mask"].detach().cpu()
                pred_intensity_cpu = pred_intensity.detach().cpu().to(torch.float32)
                if bool(mask_cpu.any()):
                    reg_true_all.append(gt_intensity_cpu[mask_cpu])
                    reg_pred_all.append(pred_intensity_cpu[mask_cpu])

        train_loss = running / max(1, total)
        train_acc = correct / max(1, total)

        yt = torch.cat(y_true_all, dim=0) if y_true_all else torch.empty((0,), dtype=torch.long)
        yp = torch.cat(y_pred_all, dim=0) if y_pred_all else torch.empty((0,), dtype=torch.long)
        train_class_summary = classification_summary(yt.tolist(), yp.tolist(), task_label_names)
        train_f1 = float(train_class_summary.get("macro_f1", 0.0))

        train_mse = 0.0
        train_mae = 0.0
        train_ccc = 0.0
        train_intensity_n = 0
        if bool(args.use_intensity) and reg_true_all and reg_pred_all:
            rt = torch.cat(reg_true_all, dim=0).to(torch.float32)
            rp = torch.cat(reg_pred_all, dim=0).to(torch.float32)
            train_intensity_n = int(rt.numel())
            if train_intensity_n > 0:
                diff = (rp - rt).to(torch.float64)
                train_mse = float((diff * diff).mean().item())
                train_mae = float(diff.abs().mean().item())
                train_ccc = _ccc(rp, rt)

        model.eval()
        v_total = 0
        v_correct = 0
        v_loss_sum = 0.0
        v_y_true_all: list[torch.Tensor] = []
        v_y_pred_all: list[torch.Tensor] = []
        v_stems_all: list[str] = []
        v_speaker_ids_all: list[str] = []
        v_probs_all: list[float] = []
        v_pred_intensity_all: list[float | None] = []
        v_gt_intensity_all: list[float | None] = []
        v_reg_pred_all: list[torch.Tensor] = []
        v_reg_true_all: list[torch.Tensor] = []
        with torch.no_grad():
            for batch in tqdm(val_loader, desc=f"Epoch {epoch}/{args.epochs} [val]"):
                nb = pin_memory and device.type == "cuda"
                flow_emb_t = batch.get("flow_emb", None)
                rgb_emb_t = batch.get("rgb_emb", None)
                text_emb_t = batch.get("text_emb", None) if bool(args.freeze_text) else None
                if str(args.video_backbone) == "videomae":
                    if not bool(args.freeze_rgb) and "rgb" not in batch:
                        raise RuntimeError("Batch is missing 'rgb'. Re-run predecode with --video-repr rgb or both.")
                    flow = None
                    rgb = batch["rgb"].to(device, non_blocking=nb) if "rgb" in batch else None
                elif str(args.video_backbone) == "dual":
                    if not bool(args.freeze_flow) and "flow" not in batch:
                        raise RuntimeError("Batch must contain raw 'flow' when the flow branch is trainable.")
                    if not bool(args.freeze_rgb) and "rgb" not in batch:
                        raise RuntimeError("Batch must contain raw 'rgb' when the RGB branch is trainable.")
                    flow = batch["flow"].to(device, non_blocking=nb) if "flow" in batch else None
                    rgb = batch["rgb"].to(device, non_blocking=nb) if "rgb" in batch else None
                else:
                    if not bool(args.freeze_flow) and "flow" not in batch:
                        raise RuntimeError("Batch is missing 'flow'. Re-run predecode with --video-repr flow or both.")
                    flow = batch["flow"].to(device, non_blocking=nb) if "flow" in batch else None
                    rgb = None

                if flow_emb_t is not None and bool(args.freeze_flow):
                    flow_emb_t = flow_emb_t.to(device, non_blocking=nb)
                else:
                    flow_emb_t = None
                if rgb_emb_t is not None and bool(args.freeze_rgb):
                    rgb_emb_t = rgb_emb_t.to(device, non_blocking=nb)
                else:
                    rgb_emb_t = None

                cached_audio_emb = batch.get("audio_emb", None)
                has_audio = "audio" in batch
                use_audio_emb = cached_audio_emb is not None and (bool(args.freeze_audio) or not has_audio)
                if use_audio_emb:
                    if has_audio:
                        wav = normalize_wav(batch["audio"], target_rms=0.1).to(device, non_blocking=nb)
                        audio_lens = batch.get("audio_lens", None)
                    else:
                        wav = torch.zeros((batch["labels"].shape[0], 1), device=device, dtype=torch.float32)
                        audio_lens = None
                else:
                    if not has_audio:
                        raise RuntimeError("Batch is missing 'audio' and no 'audio_emb' provided. Re-run predecode with --audio-repr raw or wavlm.")
                    wav = normalize_wav(batch["audio"], target_rms=0.1).to(device, non_blocking=nb)
                    audio_lens = batch["audio_lens"].to(device, non_blocking=nb)
                audio_lens_t = audio_lens.to(device, non_blocking=nb) if audio_lens is not None else None
                audio_emb_t = cached_audio_emb.to(device, non_blocking=nb) if use_audio_emb and cached_audio_emb is not None else None
                prosody = batch["prosody"].to(device, non_blocking=nb)
                y = batch["labels"].to(device, non_blocking=nb)
                if bool(args.zero_video):
                    if flow is not None:
                        flow = torch.zeros_like(flow)
                    if rgb is not None:
                        rgb = torch.zeros_like(rgb)
                    if flow_emb_t is not None:
                        flow_emb_t = torch.zeros_like(flow_emb_t)
                    if rgb_emb_t is not None:
                        rgb_emb_t = torch.zeros_like(rgb_emb_t)
                if bool(args.zero_audio):
                    wav = torch.zeros_like(wav)
                    prosody = torch.zeros_like(prosody)
                    if audio_emb_t is not None:
                        audio_emb_t = torch.zeros_like(audio_emb_t)

                mn_list = batch.get("mn", None)
                if mn_list is None:
                    raise RuntimeError("Batch is missing 'mn'. Please re-run predecode with mn saved.")
                if text_emb_t is not None:
                    text_emb_t = text_emb_t.to(device, non_blocking=nb)
                text_inputs = batch.get("text_inputs", None)
                if not bool(args.zero_text):
                    if text_inputs is not None:
                        text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}
                    elif text_emb_t is None:
                        if tokenizer is None:
                            raise RuntimeError(
                                "Text tokenizer is unavailable and batch is missing text_emb/text_inputs. "
                                "Rebuild a feature cache with text embeddings or provide local text model files."
                            )
                        text_inputs = tokenizer(
                            [
                                select_text_for_policy(
                                    full_text=str(mn_list[i]),
                                    masked_text=str(batch.get("masked_mn", [""] * len(mn_list))[i]),
                                    label_en=str(batch.get("_global_label_en", [""] * len(mn_list))[i]) or None,
                                    policy=str(args.text_policy),
                                )
                                for i in range(len(mn_list))
                            ],
                            padding=True,
                            truncation=True,
                            max_length=int(args.max_text_len),
                            return_tensors="pt",
                        )
                        text_inputs = {k: v.to(device, non_blocking=nb) for k, v in text_inputs.items()}
                else:
                    text_inputs = None
                    text_emb_t = None

                amp_ctx = _autocast_context(device, resolved_amp_mode)

                with amp_ctx:
                    if bool(args.use_intensity):
                        logits, pred_intensity = model(
                            flow,
                            wav,
                            prosody,
                            text_inputs=text_inputs,
                            return_intensity=True,
                            rgb=rgb,
                            audio_lens=audio_lens_t,
                            audio_emb=audio_emb_t,
                            flow_emb=flow_emb_t,
                            rgb_emb=rgb_emb_t,
                            text_emb=text_emb_t,
                        )
                    else:
                        logits = model(
                            flow,
                            wav,
                            prosody,
                            text_inputs=text_inputs,
                            rgb=rgb,
                            audio_lens=audio_lens_t,
                            audio_emb=audio_emb_t,
                            flow_emb=flow_emb_t,
                            rgb_emb=rgb_emb_t,
                            text_emb=text_emb_t,
                        )

                    loss = loss_fn(logits, y)

                    if bool(args.use_intensity):
                        gt_intensity = batch["intensity"].to(device, non_blocking=nb).to(torch.float32)
                        intensity_mask = batch["intensity_mask"].to(device, non_blocking=nb)
                        if intensity_mask.any():
                            pred_f = pred_intensity.to(torch.float32)[intensity_mask]
                            gt_f = gt_intensity[intensity_mask]
                            if str(args.intensity_loss).lower().strip() == "mae":
                                reg_loss = torch.abs(pred_f - gt_f).mean()
                            else:
                                reg_loss = torch.square(pred_f - gt_f).mean()
                            loss = loss + float(args.intensity_weight) * reg_loss
                v_loss_sum += loss.item() * y.size(0)
                pred = logits.argmax(dim=1)
                v_correct += (pred == y).sum().item()
                v_total += y.size(0)

                v_y_true_all.append(y.detach().cpu())
                v_y_pred_all.append(pred.detach().cpu())
                probs = torch.softmax(logits, dim=1)
                pred_probs = probs.gather(1, pred.view(-1, 1)).squeeze(1).detach().cpu()
                v_probs_all.extend(float(x) for x in pred_probs.tolist())
                v_stems_all.extend([str(x) for x in batch.get("stems", [])])
                v_speaker_ids_all.extend([str(x) for x in batch.get("speaker_id", [])])
                if bool(args.use_intensity):
                    gt_intensity_cpu = batch["intensity"].detach().cpu().to(torch.float32)
                    mask_cpu = batch["intensity_mask"].detach().cpu()
                    pred_intensity_cpu = pred_intensity.detach().cpu().to(torch.float32)
                    for sample_idx in range(int(mask_cpu.numel())):
                        if bool(mask_cpu[sample_idx].item()):
                            v_gt_intensity_all.append(float(gt_intensity_cpu[sample_idx].item()))
                            v_pred_intensity_all.append(float(pred_intensity_cpu[sample_idx].item()))
                        else:
                            v_gt_intensity_all.append(None)
                            v_pred_intensity_all.append(None)
                    if bool(mask_cpu.any()):
                        v_reg_true_all.append(gt_intensity_cpu[mask_cpu])
                        v_reg_pred_all.append(pred_intensity_cpu[mask_cpu])

        val_loss = v_loss_sum / max(1, v_total)
        val_acc = v_correct / max(1, v_total)

        vyt = torch.cat(v_y_true_all, dim=0) if v_y_true_all else torch.empty((0,), dtype=torch.long)
        vyp = torch.cat(v_y_pred_all, dim=0) if v_y_pred_all else torch.empty((0,), dtype=torch.long)
        val_class_summary = classification_summary(vyt.tolist(), vyp.tolist(), task_label_names)
        val_f1 = float(val_class_summary.get("macro_f1", 0.0))

        val_mse = 0.0
        val_mae = 0.0
        val_ccc = 0.0
        val_intensity_n = 0
        if bool(args.use_intensity) and v_reg_true_all and v_reg_pred_all:
            rt = torch.cat(v_reg_true_all, dim=0).to(torch.float32)
            rp = torch.cat(v_reg_pred_all, dim=0).to(torch.float32)
            val_intensity_n = int(rt.numel())
            if val_intensity_n > 0:
                diff = (rp - rt).to(torch.float64)
                val_mse = float((diff * diff).mean().item())
                val_mae = float(diff.abs().mean().item())
                val_ccc = _ccc(rp, rt)

        if bool(args.use_intensity):
            print(
                "Epoch {e}: train_loss={tl:.4f} train_acc={ta:.4f} train_f1={tf:.4f} "
                "val_loss={vl:.4f} val_acc={va:.4f} val_f1={vf:.4f} "
                "val_mse={vmse:.4f} val_mae={vmae:.4f} val_ccc={vccc:.4f} (n={vn})".format(
                    e=epoch,
                    tl=train_loss,
                    ta=train_acc,
                    tf=train_f1,
                    vl=val_loss,
                    va=val_acc,
                    vf=val_f1,
                    vmse=val_mse,
                    vmae=val_mae,
                    vccc=val_ccc,
                    vn=val_intensity_n,
                )
            )
        else:
            print(
                "Epoch {e}: train_loss={tl:.4f} train_acc={ta:.4f} train_f1={tf:.4f} "
                "val_loss={vl:.4f} val_acc={va:.4f} val_f1={vf:.4f}".format(
                    e=epoch,
                    tl=train_loss,
                    ta=train_acc,
                    tf=train_f1,
                    vl=val_loss,
                    va=val_acc,
                    vf=val_f1,
                )
            )

        history["train_loss"].append(float(train_loss))
        history["train_acc"].append(float(train_acc))
        history["train_f1"].append(float(train_f1))
        history["val_loss"].append(float(val_loss))
        history["val_acc"].append(float(val_acc))
        history["val_f1"].append(float(val_f1))
        history["train_per_class_recall"].append(dict(train_class_summary.get("per_class_recall", {})))
        history["val_per_class_recall"].append(dict(val_class_summary.get("per_class_recall", {})))

        if bool(args.use_intensity):
            history["train_mse"].append(float(train_mse))
            history["train_mae"].append(float(train_mae))
            history["train_ccc"].append(float(train_ccc))
            history["train_intensity_n"].append(float(train_intensity_n))
            history["val_mse"].append(float(val_mse))
            history["val_mae"].append(float(val_mae))
            history["val_ccc"].append(float(val_ccc))
            history["val_intensity_n"].append(float(val_intensity_n))

        monitor_value = float(val_f1 if str(args.monitor) == "val_f1" else val_acc)
        improved = best_epoch == 0 or monitor_value > best_monitor_value
        if improved:
            best_monitor_value = monitor_value
            best_acc = val_acc
            best_f1 = val_f1
            best_epoch = epoch
            epochs_without_improvement = 0
            best_train_summary = train_class_summary
            best_val_summary = val_class_summary
            best_ckpt_path = out_dir / "checkpoints" / "best.pt"
            ckpt = {
                "model": model.state_dict(),
                "epoch": epoch,
                "best_acc": best_acc,
                "best_f1": float(val_f1),
                "best_monitor_name": best_monitor_name,
                "best_monitor_value": float(best_monitor_value),
                "args": vars(args),
                "label_names": task_label_names,
                "task_mode": task_mode,
                "speaker_id": task_speaker_id,
                "text_policy": str(args.text_policy),
                "validity": validity_summary,
                "cache_config": ds.config,
                "resolved_runtime": {
                    "device": str(device),
                    "profile": profile.to_jsonable(),
                    "batch_size": int(resolved_batch_size),
                    "num_workers": int(resolved_num_workers),
                    "prefetch_factor": int(prefetch_factor) if prefetch_factor is not None else None,
                    "amp_mode": resolved_amp_mode,
                    "using_feature_cache": using_feature_cache,
                },
                "benchmark_tag": str(args.benchmark_tag),
                "dataset_kind": dataset_kind,
                "split_manifest": str(args.split_manifest.expanduser()) if args.split_manifest is not None else None,
                "manifest_sha256": manifest_hash,
                "ablation": str(args.ablation),
                "text_policy": str(args.text_policy),
                "zero_video": bool(args.zero_video),
                "zero_audio": bool(args.zero_audio),
                "zero_text": bool(args.zero_text),
                "best_val_summary": best_val_summary,
            }
            torch.save(ckpt, best_ckpt_path)
            print(f"Saved best checkpoint -> {best_ckpt_path}")

            val_records: list[dict[str, Any]] = []
            for idx, stem in enumerate(v_stems_all):
                y_true_idx = int(vyt[idx].item())
                y_pred_idx = int(vyp[idx].item())
                rec = {
                    "stem": stem,
                    "status": "ok",
                    "label": task_label_names[y_true_idx],
                    "pred": task_label_names[y_pred_idx],
                    "match": bool(y_true_idx == y_pred_idx),
                    "probability": float(v_probs_all[idx]) if idx < len(v_probs_all) else None,
                    "speaker_id": v_speaker_ids_all[idx] if idx < len(v_speaker_ids_all) else "UNKNOWN",
                    "task_mode": task_mode,
                    "task_speaker_id": task_speaker_id,
                }
                if bool(args.use_intensity):
                    rec["intensity_gt"] = v_gt_intensity_all[idx] if idx < len(v_gt_intensity_all) else None
                    rec["pred_intensity"] = v_pred_intensity_all[idx] if idx < len(v_pred_intensity_all) else None
                val_records.append(rec)

            val_metrics_summary = {
                "cached_dataset": str(cache_source),
                "feature_cache": str(args.feature_cache.expanduser()) if args.feature_cache is not None else None,
                "split_manifest": str(args.split_manifest.expanduser()) if args.split_manifest is not None else None,
                "subset": "val",
                "benchmark_tag": str(args.benchmark_tag),
                "checkpoint": str(best_ckpt_path),
                "task_mode": task_mode,
                "speaker_id": task_speaker_id,
                "text_policy": str(args.text_policy),
                "label_names": task_label_names,
                "attempted": len(val_records),
                "ok": len(val_records),
                "errors": 0,
                "skipped": 0,
                "accuracy_on_ok": float(val_acc),
                "macro_f1_on_ok": float(val_f1),
                "per_class_recall": val_class_summary.get("per_class_recall", {}),
                "confusion_matrix": val_class_summary.get("confusion_matrix", []),
                "support": val_class_summary.get("support", {}),
                "pred_counts": val_class_summary.get("pred_counts", {}),
                "manifest_sha256": manifest_hash,
                "manifest_summary": manifest_summary,
                "validity": validity_summary,
                "speaker_majority_baseline": speaker_baseline,
                "speaker_only_baseline": speaker_only,
            }
            _write_best_val_inference_outputs(out_dir, records=val_records, metrics_summary=val_metrics_summary)
        else:
            epochs_without_improvement += 1

        if int(args.early_stop_patience) > 0 and epochs_without_improvement >= int(args.early_stop_patience):
            print(
                f"Early stopping at epoch {epoch}: no improvement on {best_monitor_name} for {epochs_without_improvement} epoch(s)."
            )
            break

    last_ckpt = {
        "model": model.state_dict(),
        "epoch": int(epoch),
        "best_acc": float(best_acc),
        "best_f1": float(best_f1),
        "best_monitor_name": best_monitor_name,
        "best_monitor_value": float(best_monitor_value if best_monitor_value != float('-inf') else 0.0),
        "args": vars(args),
        "label_names": task_label_names,
        "task_mode": task_mode,
        "dataset_kind": dataset_kind,
        "speaker_id": task_speaker_id,
        "text_policy": str(args.text_policy),
        "validity": validity_summary,
        "cache_config": ds.config,
    }
    torch.save(last_ckpt, out_dir / "checkpoints" / "last.pt")

    metrics_payload: dict[str, Any] = dict(history)
    metrics_payload["meta"] = {
        "benchmark_tag": str(args.benchmark_tag),
        "cached_dataset": str(cache_source),
        "num_shards": len(shard_paths),
        "split_mode": str(args.split_mode),
        "split_manifest": str(args.split_manifest.expanduser()) if args.split_manifest is not None else None,
        "manifest_sha256": manifest_hash,
        "task_mode": task_mode,
        "speaker_id": task_speaker_id,
        "text_policy": str(args.text_policy),
        "label_names": task_label_names,
        "train_size": len(train_indices),
        "val_size": len(val_indices),
        "ablation": str(args.ablation),
        "zero_video": bool(args.zero_video),
        "zero_audio": bool(args.zero_audio),
        "zero_text": bool(args.zero_text),
        "args": _to_jsonable(vars(args)),
        "cache_config": _to_jsonable(ds.config),
        "device": str(device),
        "runtime_profile": profile.to_jsonable(),
        "resolved_batch_size": int(resolved_batch_size),
        "resolved_num_workers": int(resolved_num_workers),
        "resolved_prefetch_factor": int(prefetch_factor) if prefetch_factor is not None else None,
        "amp_mode": resolved_amp_mode,
        "using_feature_cache": using_feature_cache,
    }
    if manifest_summary:
        metrics_payload["meta"]["manifest_summary"] = manifest_summary
    if speaker_baseline is not None:
        metrics_payload["speaker_majority_baseline"] = speaker_baseline
    if speaker_only is not None:
        metrics_payload["speaker_only_baseline"] = speaker_only
    metrics_payload["validity"] = validity_summary
    metrics_payload["best"] = {
        "epoch": int(best_epoch),
        "best_acc": float(best_acc),
        "best_f1": float(best_f1),
        "best_monitor_name": best_monitor_name,
        "best_monitor_value": float(best_monitor_value if best_monitor_value != float("-inf") else 0.0),
        "best_train_summary": best_train_summary,
        "best_val_summary": best_val_summary,
    }

    _save_metrics_and_plots(out_dir, metrics_payload)
    _write_results_summary(out_dir, metrics_payload)


if __name__ == "__main__":
    main()
